Repository hmislk/hmis, pull requests merged in 2024-12, with the labels that each got.

#9281 Issue#9280
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/java/com/divudi/data/ReportTemplateRow.java
  src/main/webapp/reports/collectionCenterReports/route_analysis_report.xhtml
  src/main/webapp/resources/ezcomp/bundles/routeAnalysisDetailBills.xhtml
  src/main/webapp/resources/ezcomp/bundles/routeAnalysisSummeryBills.xhtml
Labels: Report

#9326 Issue#9325
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/webapp/reports/financialReports/payment_settlement_report.xhtml
Labels: Report

#9354 Issue#9352
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/java/com/divudi/data/ReportTemplateRow.java
  src/main/webapp/reports/lab/sample_carrier.xhtml
Labels: Report

#9389 Issue#9388
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/java/com/divudi/data/ReportTemplateRowBundle.java
  src/main/webapp/reports/collectionCenterReports/collection_center_bill_wise_detail_report.xhtml
Labels: Report

#9482 Issue#9481
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/java/com/divudi/data/ReportTemplateRowBundle.java
  src/main/webapp/reports/financialReports/credit_invoice_dispatch_report.xhtml
  src/main/webapp/reports/lab/external_laboratory_workload.xhtml
Labels: Report

#9521 Issue#9520
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/java/com/divudi/data/ReportTemplateRowBundle.java
  src/main/webapp/reports/financialReports/opd_and_inward_due_report.xhtml
Labels: Report

#9546 Issue#9545 debtor reports
  src/main/java/com/divudi/bean/common/CreditCompanyDueController.java
  src/main/java/com/divudi/ejb/CreditBean.java
  src/main/webapp/reports/financialReports/cash_inward_excess.xhtml
  src/main/webapp/reports/financialReports/cash_inward_excess_age.xhtml
  src/main/webapp/reports/financialReports/credit_company_inward_excess.xhtml
  src/main/webapp/reports/financialReports/credit_company_inward_excess_age.xhtml
  src/main/webapp/reports/financialReports/inward_due_age.xhtml
  src/main/webapp/reports/financialReports/inward_due_age_credit_company.xhtml
  src/main/webapp/reports/financialReports/inward_due_age_credit_company_detail.xhtml
  src/main/webapp/reports/financialReports/inward_due_search.xhtml
  src/main/webapp/reports/financialReports/inward_due_search_credit_company.xhtml
Labels: Report

#9581 Issue#9580 opd weekly summary report
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/webapp/reports/managementReports/opd_weekly.xhtml
Labels: Report

#9583 Issue#9441 Collection Center Bill Wise Detail bugfix
  src/main/java/com/divudi/entity/Bill.java
Labels: bug

#9587 Issue#9577 GRN report Improvement
  src/main/java/com/divudi/bean/common/BillSearch.java
  src/main/java/com/divudi/bean/pharmacy/PharmacyController.java
  src/main/resources/META-INF/persistence.xml
  src/main/webapp/reports/inventoryReports/grn_report.xhtml
Labels: Report

#9591 Route analysis report without graphs
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/webapp/reports/collectionCenterReports/route_analysis_report.xhtml
  src/main/webapp/resources/ezcomp/bundles/routeAnalysisDetailBills.xhtml
  src/main/webapp/resources/ezcomp/bundles/routeAnalysisSummeryBills.xhtml
Labels: Report

#9610 Issue#9562 Purchase Rate & Purchase Value columns for Transfer Issue By Bill Item Report
  src/main/webapp/pharmacy/pharmacy_report_transfer_issue_bill_item_1.xhtml
Labels: COOP Hospital

#9641 Issue#9419 sample career report bugfixes
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/java/com/divudi/bean/lab/PatientInvestigationController.java
  src/main/java/com/divudi/data/ReportTemplateRow.java
  src/main/java/com/divudi/entity/lab/PatientInvestigation.java
  src/main/webapp/reports/financialReports/credit_invoice_dispatch_report.xhtml
  src/main/webapp/reports/lab/sample_carrier.xhtml
  src/main/webapp/resources/sql/bills.sql
Labels: Report

#9654 Issue#9337 staff welfare report bug fixes
  src/main/java/com/divudi/bean/common/SearchController.java
  src/main/webapp/reports/financialReports/staff_welfare.xhtml
  src/main/webapp/resources/ezcomp/bundles/staffWelfareBillItems.xhtml
  src/main/webapp/resources/ezcomp/bundles/staffWelfareBills.xhtml
Labels: bug

#9655 Issue#9649 collection center bill wise detail report bugfixes
  src/main/webapp/reports/collectionCenterReports/collection_center_bill_wise_detail_report.xhtml
Labels: bug

#9694 Issue#9428-Collection-Center-Book-Wise-Detail-bugfixes
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/webapp/reports/collectionCenterReports/collection_centre_book_wise_detail.xhtml
Labels: bug

#9695 Issue#9004 improvements in package report
  src/main/webapp/reports/financialReports/package_report.xhtml
  src/main/webapp/reports/financialReports/staff_welfare.xhtml
  src/main/webapp/resources/ezcomp/bundles/packageBillItems.xhtml
Labels: bug

#9715 Issue#9550 external laboratory work load
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/java/com/divudi/data/ReportTemplateRowBundle.java
  src/main/webapp/reports/lab/external_laboratory_workload.xhtml
Labels: bug

#9722 Issue#9653 -Charts in route analysis report
  src/main/java/com/divudi/bean/common/ChartJsView.java
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/webapp/reports/collectionCenterReports/route_analysis_report.xhtml
Labels: bug

#9730 Issue #9729 opd weekly report detail implementation
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/webapp/reports/managementReports/opd_weekly.xhtml
Labels: Report

#9764 Issue#9731-payment settlement report bugfixes
  src/main/webapp/reports/financialReports/payment_settlement_report.xhtml
Labels: bug

#9765 Issue#9761- sample carrier report
  src/main/java/com/divudi/bean/common/ReportsController.java
Labels: bug

#9772 External Laboratory Workload Report #9762
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/webapp/reports/lab/external_laboratory_workload.xhtml
Labels: bug

#9774 Issue#9773 Discount Report
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/java/com/divudi/data/ReportTemplateRowBundle.java
  src/main/webapp/reports/financialReports/discount.xhtml
Labels: Report

#9790 Issue#9616 debtor analysis excess age
  src/main/webapp/reports/financialReports/cash_inward_excess_age.xhtml
Labels: bug

#9791 Issue#9615 debtor analysis excess search
  src/main/webapp/reports/financialReports/cash_inward_excess.xhtml
Labels: bug

#9792 Debtor Analysis-Excess Age (Credit Company) #9614
  src/main/webapp/reports/financialReports/credit_company_inward_excess_age.xhtml
Labels: bug

#9833 Issue#9680 collection center bill wise detail report
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/webapp/reports/collectionCenterReports/collection_center_bill_wise_detail_report.xhtml
Labels: bug

#9835 Debtor Analysis-Due Search (Credit Company) #9600
  src/main/java/com/divudi/bean/common/CreditCompanyDueController.java
  src/main/webapp/reports/financialReports/inward_due_search_credit_company.xhtml
Labels: bug

#9865 Issues#9800|#9804|#9761
  .github/workflows/coop_dev_ci_cd.yml
  src/main/java/com/divudi/bean/common/MedicalPackageItemController.java
  src/main/java/com/divudi/bean/common/PackageItemController.java
  src/main/java/com/divudi/bean/common/PatientController.java
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/java/com/divudi/bean/common/SessionController.java
  src/main/java/com/divudi/bean/common/TriggerSubscriptionController.java
  src/main/java/com/divudi/bean/common/UserRoleTriggerSubscriptionController.java
  src/main/java/com/divudi/bean/common/WebUserController.java
  src/main/java/com/divudi/bean/common/WebUserRoleUserController.java
  src/main/java/com/divudi/bean/common/membership/FamilyController.java
  src/main/java/com/divudi/bean/emr/DataUploadController.java
  src/main/java/com/divudi/bean/membership/MembershipController.java
  src/main/java/com/divudi/bean/opd/OpdBillController.java
  src/main/java/com/divudi/bean/pharmacy/PharmacySaleController.java
  src/main/java/com/divudi/entity/Family.java
  src/main/webapp/dealerPayment/pay_supplier.xhtml
  src/main/webapp/membership/analytics/index.xhtml
  src/main/webapp/membership/analytics/lists/families.xhtml
  src/main/webapp/membership/analytics/lists/members.xhtml
  src/main/webapp/membership/family_membership_manage.xhtml
  src/main/webapp/membership/family_membership_search.xhtml
  src/main/webapp/membership/individual_membership_new.xhtml
  src/main/webapp/membership/patient.xhtml
  src/main/webapp/membership/reports.xhtml
  src/main/webapp/reports/collectionCenterReports/route_analysis_report.xhtml
  src/main/webapp/reports/managementReports/opd_weekly.xhtml
  src/main/webapp/resources/css/ohmis.css
  src/main/webapp/resources/ezcomp/menu.xhtml
Labels: bug
