Repository hmislk/hmis, pull requests merged in 2025-01, with the labels that each got.

#9955 OPD Weekly Report #9886
  src/main/java/com/divudi/bean/common/ReportsController.java
Labels: bug

#10011 9972 discount report bug fixes
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/java/com/divudi/data/ReportTemplateRowBundle.java
  src/main/webapp/reports/financialReports/discount.xhtml
Labels: bug

#10068 10034 discount report bugfixes
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/webapp/reports/financialReports/discount.xhtml
Labels: bug

#10067 9964 staff welfare report bugfixes
  src/main/java/com/divudi/bean/common/SearchController.java
  src/main/webapp/reports/financialReports/staff_welfare.xhtml
Labels: bug

#10104 9880 Route analysis report bugfixes
  src/main/java/com/divudi/bean/common/ReportsController.java
Labels: bug

#10109 10003 Collection center bill wise detail report bugfixes
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/webapp/reports/collectionCenterReports/collection_center_bill_wise_detail_report.xhtml
Labels: bug

#10120 9845 payment settlement report
  src/main/webapp/reports/financialReports/payment_settlement_report.xhtml
Labels: bug

#10122 10107 discount report
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/webapp/reports/financialReports/discount.xhtml
Labels: bug

#10130 9799 external laboratory workload report caching issue
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/java/com/divudi/facade/AbstractFacade.java
Labels: bug

#10141 9867 debtor analysis due reports bugfixes
  src/main/java/com/divudi/bean/common/CreditCompanyDueController.java
  src/main/webapp/reports/financialReports/inward_due_search.xhtml
  src/main/webapp/reports/financialReports/inward_due_search_credit_company.xhtml
Labels: bug

#10142 10139 Staff welfare fix
  src/main/webapp/reports/financialReports/staff_welfare.xhtml
Labels: bug

#10156 10154 route analysis report
  src/main/java/com/divudi/bean/common/ReportsController.java
Labels: bug

#10177 9963 Collection Center Wise Invoice Report Bugfixes
  src/main/java/com/divudi/bean/common/ReportsController.java
Labels: bug

#10182 OPD Weekly Report UI Text fix
  src/main/webapp/reports/managementReports/opd_weekly.xhtml
Labels: bug

#10185 10162 collection center bill wise detail report bugfix
  src/main/java/com/divudi/bean/common/ReportsController.java
Labels: bug

#10188 10162 collection center bill wise detail report fixes
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/webapp/reports/collectionCenterReports/collection_center_bill_wise_detail_report.xhtml
Labels: bug

#10270 Expiry item report bugfixes
  src/main/java/com/divudi/bean/report/PharmacyReportController.java
  src/main/webapp/reports/inventoryReports/expiry_item.xhtml
Labels: bug

#10277 Collection Center Bill Wise Detail bugfixes
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/webapp/reports/collectionCenterReports/collection_center_bill_wise_detail_report.xhtml
Labels: bug

#10290 10280 stock ledger report bug fix
  .github/workflows/coop_dev_ci_cd.yml
  src/main/java/com/divudi/bean/pharmacy/PharmacyBillSearch.java
  src/main/java/com/divudi/entity/pharmacy/StockHistory.java
  src/main/webapp/pharmacy/pharmacy_cancel_bill_retail.xhtml
  src/main/webapp/pharmacy/pharmacy_reprint_bill_sale.xhtml
  src/main/webapp/pharmacy/pharmacy_search_sale_bill.xhtml
  src/main/webapp/reports/inventoryReports/stock_ledger.xhtml
Labels: bug

#10301 #9370 Site Wise Lab Format Footer need to Change
  src/main/java/com/divudi/bean/lab/PatientReportController.java
  src/main/java/com/divudi/bean/lab/ReportFormatController.java
  src/main/webapp/admin/lims/investigation.xhtml
  src/main/webapp/admin/lims/report_template.xhtml
  src/main/webapp/admin/lims/report_template_names.xhtml
  src/main/webapp/lab/generate_barcode_p.xhtml
  src/main/webapp/lab/patient_report.xhtml
Labels: Lab, New Feature

#10312 expiry item report bugfix
  src/main/java/com/divudi/bean/report/PharmacyReportController.java
Labels: bug

#10318 10317 GRN report
  src/main/java/com/divudi/bean/pharmacy/PharmacyController.java
  src/main/webapp/reports/inventoryReports/grn.xhtml
Labels: Report

#10321 Expiry item report bugfix
  src/main/java/com/divudi/bean/report/PharmacyReportController.java
Labels: bug
