Repository hmislk/hmis, pull requests merged in 2025-08, with the labels that each got.

#14435 Birth format is correction in Member Upload
  src/main/java/com/divudi/bean/emr/DataUploadController.java
  src/main/webapp/membership/upload_members.xhtml
Labels: bug

#14439 total purchase value and total sale value fix
  src/main/java/com/divudi/bean/pharmacy/PharmacyController.java
  src/main/webapp/reports/inventoryReports/grn_report.xhtml
Labels: bug

#14449 Fix output label alignment
  src/main/webapp/pharmacy/pharmacy_transfer_issue_direct_department.xhtml
Labels: codex

#14451 Add stock autocomplete colour toggle
  developer_docs/navigation/pharmacy_navigation.md
  src/main/java/com/divudi/bean/common/ConfigOptionApplicationController.java
Labels: codex

#14452 Add Excel export to application options list
  src/main/webapp/admin/institutions/admin_mange_application_options.xhtml
Labels: codex

#14453 Fix inconsistent config keys
  src/main/java/com/divudi/bean/pharmacy/TransferReceiveController.java
  src/main/webapp/resources/pharmacy/transferIssue.xhtml
  src/main/webapp/resources/pharmacy/transferReceive.xhtml
Labels: codex

#14457 Improve transfer report UIs
  src/main/webapp/pharmacy/reports/disbursement_reports/pharmacy_report_transfer_issue_bill_dto.xhtml
  src/main/webapp/pharmacy/reports/disbursement_reports/pharmacy_report_transfer_issue_bill_summery.xhtml
  src/main/webapp/pharmacy/reports/disbursement_reports/pharmacy_report_transfer_receive_bill.xhtml
  src/main/webapp/pharmacy/reports/disbursement_reports/pharmacy_report_transfer_receive_bill_item.xhtml
  src/main/webapp/pharmacy/reports/disbursement_reports/pharmacy_report_transfer_receive_bill_summery.xhtml
Labels: codex

#14455 #13588 cogs stock consumption
  src/main/java/com/divudi/bean/report/PharmacyReportController.java
  src/main/webapp/reports/inventoryReports/stock_consumption.xhtml
Labels: Report

#14479 feat: prevent self department transfer
  src/main/java/com/divudi/bean/pharmacy/TransferIssueController.java
Labels: codex

#14480 feat: track web user password history
  src/main/java/com/divudi/bean/common/WebUserController.java
  src/main/java/com/divudi/core/entity/WebUserPasswordHistory.java
  src/main/java/com/divudi/core/facade/WebUserPasswordHistoryFacade.java
Labels: codex

#14481 Add prevent password reuse config option
  src/main/java/com/divudi/bean/common/ConfigOptionApplicationController.java
  src/main/java/com/divudi/bean/common/ConfigOptionController.java
Labels: codex

#14482 feat: enforce password history
  src/main/java/com/divudi/bean/common/SessionController.java
  src/main/java/com/divudi/bean/common/WebUserController.java
Labels: codex

#14501 feat: add expense removal actions
  src/main/java/com/divudi/bean/pharmacy/GrnCostingController.java
  src/main/java/com/divudi/bean/pharmacy/PharmacyDirectPurchaseController.java
  src/main/webapp/pharmacy/direct_purchase.xhtml
  src/main/webapp/pharmacy/pharmacy_grn_costing.xhtml
  src/main/webapp/resources/images/icons/trash.svg
Labels: codex

#14513 Fix transfer receive summary department mapping
  src/main/java/com/divudi/bean/common/BillBeanController.java
Labels: codex

#14514 feat: track purchase value on transfer receive reports
  src/main/java/com/divudi/bean/pharmacy/ReportsTransfer.java
  src/main/java/com/divudi/core/data/dto/PharmacyTransferReceiveDTO.java
Labels: codex

#14418 #14135 cogs cost rate value
  src/main/webapp/reports/inventoryReports/bht_issue.xhtml
  src/main/webapp/reports/inventoryReports/grn_cash.xhtml
  src/main/webapp/reports/inventoryReports/grn_credit.xhtml
  src/main/webapp/reports/inventoryReports/ip_drug_return.xhtml
  src/main/webapp/reports/inventoryReports/op_drug_return.xhtml
  src/main/webapp/reports/inventoryReports/opd_credit.xhtml
  src/main/webapp/reports/inventoryReports/opd_sale.xhtml
  src/main/webapp/reports/inventoryReports/opd_sale_cash.xhtml
  src/main/webapp/reports/inventoryReports/purchase_return.xhtml
  src/main/webapp/reports/inventoryReports/stock_consumption.xhtml
  src/main/webapp/reports/inventoryReports/transfer_issue.xhtml
  src/main/webapp/reports/inventoryReports/transfer_receive.xhtml
Labels: Report

#14527 feat: add transfer receive reprint navigation by id
  src/main/java/com/divudi/bean/pharmacy/PharmacyBillSearch.java
Labels: codex

#14540 fix: round balance to two decimal places in cashier bill
  src/main/webapp/resources/pharmacy/sale_for_cashier_bill_five_five_custom_3_.xhtml
Labels: bug

#14546 Signed-off-by: Lawan Samarasekara <lawan.chaamindu1234@gmail.com>
  src/main/webapp/resources/pharmacy/transferReceive.xhtml
Labels: COOP Hospital, Hot Fix

#14530 14529 - Enhance Patient Report with Additional Variables
  src/main/java/com/divudi/bean/lab/PatientReportController.java
  src/main/java/com/divudi/core/entity/lab/PatientReport.java
  src/main/webapp/lab/patient_report.xhtml
  src/main/webapp/resources/ezcomp/common_report.xhtml
Labels: Lab

#14548 14543 retail rate table heading should change as purchase rate in transfer receive note
  src/main/webapp/resources/pharmacy/transferReceive.xhtml
Labels: COOP Hospital

#14557 fix: adjust discount calculation for cancelled and refund bills #14330
  src/main/java/com/divudi/bean/report/ServiceSummery.java
  src/main/webapp/reportInstitution/report_opd_pharmacy_staff_welfare.xhtml
Labels: bug

#14556 add sale price and sale value columns to return without receipt #14524
  src/main/webapp/resources/pharmacy/pharmacyReturnWithoutTresingA4.xhtml
Labels: bug

#14715 Allow measurement units to appear in multiple unit lists
  src/main/java/com/divudi/bean/pharmacy/MeasurementUnitController.java
Labels: codex

#14717 Fix image deletion in OPD visit
  src/main/java/com/divudi/bean/clinical/PastPatientEncounterController.java
  src/main/java/com/divudi/bean/clinical/PatientEncounterController.java
  src/main/java/com/divudi/bean/inward/InpatientClinicalDataController.java
Labels: codex

#14728 feat: add consignment flag to pharmacy bills
  db/migration/04_add_consignment_column_to_bill.sql
  src/main/java/com/divudi/bean/common/ConfigOptionApplicationController.java
  src/main/java/com/divudi/bean/pharmacy/GrnCostingController.java
  src/main/java/com/divudi/bean/pharmacy/PharmacyDirectPurchaseController.java
  src/main/java/com/divudi/bean/pharmacy/PurchaseOrderController.java
  src/main/java/com/divudi/bean/pharmacy/PurchaseOrderRequestController.java
  src/main/java/com/divudi/core/entity/Bill.java
  src/main/webapp/pharmacy/direct_purchase.xhtml
  src/main/webapp/pharmacy/pharmacy_grn_costing.xhtml
  src/main/webapp/pharmacy/pharmacy_purchase_order_list_for_recieve.xhtml
  src/main/webapp/pharmacy/pharmacy_purhcase_order_approving.xhtml
  src/main/webapp/pharmacy/pharmacy_purhcase_order_list_to_approve.xhtml
  src/main/webapp/pharmacy/pharmacy_purhcase_order_list_to_finalize.xhtml
  src/main/webapp/pharmacy/pharmacy_purhcase_order_request.xhtml
  src/main/webapp/resources/pharmacy/direct_purhcase_with_costing.xhtml
  src/main/webapp/resources/pharmacy/grn_with_costing.xhtml
  src/main/webapp/resources/pharmacy/po.xhtml
Labels: codex

#14754 feat: enable substitution selection in transfer issue
  src/main/java/com/divudi/bean/pharmacy/TransferIssueController.java
  src/main/webapp/pharmacy/pharmacy_transfer_issue.xhtml
Labels: codex

#14748 Opd and pharmacy staff welfare bills coop hotfix
  src/main/java/com/divudi/bean/report/ServiceSummery.java
  src/main/java/com/divudi/ejb/BillNumberGenerator.java
  src/main/webapp/opd/opd_batch_bill_print.xhtml
  src/main/webapp/pharmacy/pharmacy_transfer_issue.xhtml
  src/main/webapp/reportInstitution/report_opd_pharmacy_staff_welfare.xhtml
  src/main/webapp/resources/pharmacy/grn.xhtml
Labels: COOP Hospital, Hot Fix

#14751 14750 cc repayment bill search view bill and print reprint
  src/main/java/com/divudi/bean/common/CollectingCentrePaymentController.java
  src/main/webapp/collecting_centre/cc_repayment_bill_reprint.xhtml
  src/main/webapp/collecting_centre/collecting_centre_repayment_bill_search.xhtml
  src/main/webapp/collecting_centre/index.xhtml
  src/main/webapp/resources/bill/A4PaperCCRepayment.xhtml
Labels: Ruhunu Hospital, Collecting Centres

#14752 Fixed - 14714 cc-book-adding-view-book-no-duplicate-error-message-duplicate-bill-book-priviously-added-cc-code-need-to-show-in-error-message
  src/main/java/com/divudi/bean/channel/AgentReferenceBookController.java
  src/main/webapp/collecting_centre/cc_referece_book.xhtml
Labels: Ruhunu Hospital, Collecting Centres

#14767 Swagger api doc integration
  src/main/webapp/resources/ezcomp/menu.xhtml
  src/main/webapp/resources/swagger-ui/carecode-channceling-apis.yaml
  src/main/webapp/resources/swagger-ui/index.css
  src/main/webapp/resources/swagger-ui/index.html
  src/main/webapp/resources/swagger-ui/logo only.png
  src/main/webapp/resources/swagger-ui/oauth2-redirect.html
  src/main/webapp/resources/swagger-ui/swagger-initializer.js
  src/main/webapp/resources/swagger-ui/swagger-ui-bundle.js
  src/main/webapp/resources/swagger-ui/swagger-ui-es-bundle-core.js
  src/main/webapp/resources/swagger-ui/swagger-ui-es-bundle.js
  src/main/webapp/resources/swagger-ui/swagger-ui-standalone-preset.js
  src/main/webapp/resources/swagger-ui/swagger-ui.css
  src/main/webapp/resources/swagger-ui/swagger-ui.js
Labels: Channelling, Api

#14772 Add privilege for receipt paper type change
  src/main/java/com/divudi/bean/common/UserPrivilageController.java
  src/main/java/com/divudi/core/data/Privileges.java
Labels: codex

#14773 Grn report. #14723
  src/main/java/com/divudi/bean/pharmacy/PharmacyController.java
  src/main/java/com/divudi/core/data/table/String1Value1.java
  src/main/webapp/reports/inventoryReports/grn_report.xhtml
Labels: bug

#14774 Restrict paper type selection to privileged users
  src/main/webapp/clinical/clinical_pharmacy_sale.xhtml
  src/main/webapp/pharmacy_wholesale/pharmacy_bill_retail_sale.xhtml
  src/main/webapp/pharmacy_wholesale/pharmacy_bill_retail_sale_1.xhtml
  src/main/webapp/pharmacy_wholesale/pharmacy_bill_retail_sale_2.xhtml
  src/main/webapp/pharmacy_wholesale/pharmacy_bill_retail_sale_3.xhtml
Labels: codex

#14782 feat: add pharmacy disposal direct issue tile
  src/main/java/com/divudi/core/data/Icon.java
  src/main/webapp/home.xhtml
  src/main/webapp/resources/images/home/pharmacy-disposal-issue.svg
Labels: codex

#14784 14781 create investigation bill list report
  src/main/java/com/divudi/bean/lab/LaborataryReportController.java
  src/main/java/com/divudi/core/data/dto/PatientInvestigationDTO.java
  src/main/java/com/divudi/core/data/reports/LaboratoryReport.java
  src/main/webapp/reportLab/bill_item_list.xhtml
  src/main/webapp/reportLab/bill_item_list_print.xhtml
  src/main/webapp/reportLab/lab_summeries_index.xhtml
Labels: Lab, Report, COOP Hospital

#14792 Fix validation for GRN returns exceeding purchase quantities
  src/main/java/com/divudi/bean/pharmacy/GrnReturnWithCostingController.java
Labels: codex

#14796 fix: resolve purchase order email body generation
  src/main/java/com/divudi/bean/pharmacy/PurchaseOrderRequestController.java
  src/main/webapp/pharmacy/pharmacy_purhcase_order_approving.xhtml
  src/main/webapp/pharmacy/pharmacy_purhcase_order_request.xhtml
Labels: codex

#14801 14799 test wise regent cost report
  src/main/java/com/divudi/bean/lab/LaborataryReportController.java
  src/main/java/com/divudi/core/data/dto/TestCountDTO.java
  src/main/webapp/reportLab/lab_summeries_index.xhtml
  src/main/webapp/reportLab/laboratary_summary.xhtml
  src/main/webapp/reportLab/test_wise_regent_cost_report.xhtml
  src/main/webapp/reportLab/test_wise_regent_cost_report_print.xhtml
Labels: Lab, Report, COOP Hospital

#14807 14806 optimize the laboratory summary in lab analytics
  src/main/java/com/divudi/bean/opd/OpdReportController.java
  src/main/java/com/divudi/core/data/IncomeBundle.java
  src/main/java/com/divudi/core/data/dto/BillItemDTO.java
  src/main/java/com/divudi/core/data/reports/LaboratoryReport.java
  src/main/webapp/reportLab/lab_summeries_index.xhtml
  src/main/webapp/reportLab/laboratary_summary.xhtml
  src/main/webapp/reportLab/laboratary_summary_print.xhtml
Labels: Lab, Report, COOP Hospital

#14819 fixed - cc-repayment-bill-search-view-bill-and-print-reprint
  src/main/webapp/collecting_centre/collecting_centre_repayment_bill_search.xhtml
Labels: Ruhunu Hospital, Payment, Collecting Centres

#14831 Grn report #14803
  src/main/java/com/divudi/bean/pharmacy/PharmacyController.java
  src/main/webapp/reports/inventoryReports/grn_report.xhtml
Labels: bug

#14840 Stock ledger #14534
  src/main/java/com/divudi/bean/report/PharmacyReportController.java
  src/main/java/com/divudi/core/data/reports/InventoryReports.java
  src/main/webapp/reports/inventoryReports/stock_ledger.xhtml
Labels: bug

#14847 Stock transfer report #14833
  src/main/java/com/divudi/bean/pharmacy/PharmacyController.java
  src/main/java/com/divudi/core/data/dataStructure/PharmacySummery.java
  src/main/webapp/reports/inventoryReports/stock_transfer_report.xhtml
Labels: bug

#14827 Added support for additional department types in pharmacy transactions
  src/main/java/com/divudi/bean/common/SessionController.java
Labels: COOP Hospital, Hot Fix

#14868 Bht issue by bill report improvements#14837
  src/main/java/com/divudi/bean/common/BillController.java
  src/main/java/com/divudi/bean/pharmacy/ReportsTransfer.java
  src/main/java/com/divudi/core/data/dto/PharmacyTransferIssueBillDTO.java
  src/main/webapp/pharmacy/pharmacy_report_bht_issue_bill.xhtml
  src/main/webapp/pharmacy/pharmacy_report_bht_issue_bill_print.xhtml
Labels: enhancement

#14873 All cashier, cashier summary, cashier details report #14737
  src/main/java/com/divudi/bean/common/EnumController.java
  src/main/java/com/divudi/bean/report/PharmacyReportController.java
  src/main/webapp/reports/inventoryReports/slow_fast_none_movement.xhtml
Labels: bug

#14877 Improve in ob agent payment process
  src/main/java/com/divudi/bean/channel/OnlineBookingAgentController.java
  src/main/java/com/divudi/service/ChannelService.java
  src/main/java/com/divudi/ws/channel/ChannelApi.java
  src/main/webapp/channel/channel_booking.xhtml
  src/main/webapp/channel/channel_payment_staff_bill.xhtml
  src/main/webapp/channel/session_instance.xhtml
  src/main/webapp/online_booking_agent_management/OB_agency_direct_fund_bill_search.xhtml
  src/main/webapp/online_booking_agent_management/OB_agent_paid_bill_reprint.xhtml
  src/main/webapp/online_booking_agent_management/OB_payment_handle.xhtml
  src/main/webapp/online_booking_agent_management/index.xhtml
  src/main/webapp/online_booking_agent_management/online_booking_agency_analytics.xhtml
  src/main/webapp/online_booking_agent_management/view_all_online_bookings.xhtml
  src/main/webapp/resources/ezcomp/menu.xhtml
  src/main/webapp/resources/swagger-ui/index.html
Labels: Channelling

#14896 14842 need to improve investigation month end details report hotfix
  src/main/java/com/divudi/bean/lab/InvestigationController.java
  src/main/java/com/divudi/bean/report/InvestigationMonthSummeryOwnController.java
  src/main/java/com/divudi/core/data/IncomeRow.java
  src/main/java/com/divudi/core/data/dataStructure/InvestigationDetails.java
  src/main/java/com/divudi/core/data/dto/InvestigationDTO.java
  src/main/webapp/reportLab/report_lab.xhtml
  src/main/webapp/reportLab/report_lab_investigation_month_end_detail.xhtml
Labels: Ruhunu Hospital, Hot Fix

#14898 feat: show pharmacy item history
  src/main/java/com/divudi/bean/pharmacy/PharmacyDirectPurchaseController.java
  src/main/webapp/pharmacy/direct_purchase.xhtml
Labels: codex

#14891 Procurement direct purchase voucher #14386
  src/main/webapp/dealerPayment/view_supplier_payment_voucher.xhtml
  src/main/webapp/resources/bill/grn_payment_with_pre_bill.xhtml
  src/main/webapp/resources/pharmacy/purhcase.xhtml
Labels: Pharmacy, COOP Hospital

#14897 14842 need to improve investigation month end details report
  src/main/java/com/divudi/bean/lab/InvestigationController.java
  src/main/java/com/divudi/bean/report/InvestigationMonthSummeryOwnController.java
  src/main/java/com/divudi/core/data/IncomeRow.java
  src/main/java/com/divudi/core/data/dataStructure/InvestigationDetails.java
  src/main/java/com/divudi/core/data/dto/InvestigationDTO.java
  src/main/webapp/reportLab/report_lab.xhtml
  src/main/webapp/reportLab/report_lab_investigation_month_end_detail.xhtml
Labels: Report, Ruhunu Hospital

#14909 Fixed - 14908-refactor-test-wise-reagent-cost-report-query-structure
  src/main/java/com/divudi/bean/lab/LaborataryReportController.java
Labels: Report, COOP Hospital

#14913 14911 add validation for double click errors in pharmacy
  src/main/java/com/divudi/bean/pharmacy/PharmacySaleBhtController.java
  src/main/webapp/inward/pharmacy_bill_issue_bht.xhtml
  src/main/webapp/pharmacy/pharmacy_transfer_issue.xhtml
  src/main/webapp/pharmacy/pharmacy_transfer_issue_direct_department.xhtml
  src/main/webapp/ward/ward_pharmacy_bht_issue.xhtml
Labels: Pharmacy

#14914 feat: add privilege tree search
  src/main/java/com/divudi/bean/common/UserPrivilageController.java
  src/main/webapp/admin/users/user_privileges.xhtml
Labels: codex

#14916 feat(pharmacy): toggle print formats for direct purchase
  src/main/java/com/divudi/bean/pharmacy/PharmacyDirectPurchaseController.java
  src/main/webapp/pharmacy/direct_purchase.xhtml
Labels: codex

#14918 feat: add pharmacy transfer rates privilege
  src/main/java/com/divudi/core/data/Privileges.java
Labels: codex

#14919 Gate pharmacy transfer rate fields by privilege
  src/main/webapp/pharmacy/pharmacy_transfer_issue.xhtml
  src/main/webapp/pharmacy/pharmacy_transfer_issue_direct_department.xhtml
  src/main/webapp/pharmacy/pharmacy_transfer_receive.xhtml
  src/main/webapp/pharmacy/pharmacy_transfer_request.xhtml
Labels: codex

#14920 fixed - need-new-lab-report-for-view-inpatient-details
  src/main/java/com/divudi/core/data/IncomeBundle.java
  src/main/webapp/reportLab/laboratary_income_report.xhtml
  src/main/webapp/reportLab/laboratary_income_report_print.xhtml
Labels: Report, COOP Hospital

#14932 Restrict transfer rate visibility to privileged users
  src/main/webapp/resources/pharmacy/pharmacy_transfer_issue_receipt.xhtml
  src/main/webapp/resources/pharmacy/pharmacy_transfer_receive_receipt.xhtml
  src/main/webapp/resources/pharmacy/transfeRecieve_detailed.xhtml
  src/main/webapp/resources/pharmacy/transferIssue.xhtml
  src/main/webapp/resources/pharmacy/transferIssue_detailed.xhtml
  src/main/webapp/resources/pharmacy/transferReceive.xhtml
Labels: codex

#14933 Handle null and whitespace frequency names in dose calculation
  src/main/java/com/divudi/ejb/PrescriptionToItemService.java
  src/test/java/com/divudi/ejb/PrescriptionToItemServiceTest.java
Labels: codex

#14945 Use autocomplete for VMP selection
  src/main/webapp/pharmacy/admin/vmp.xhtml
Labels: codex

#14954 Use VMP name for generic field in stock DTO query
  src/main/java/com/divudi/bean/pharmacy/ReportsStock.java
Labels: codex

#14955 Align totals in pharmacy department stock report footer
  src/main/webapp/pharmacy/pharmacy_report_department_stock_by_batch_dto.xhtml
Labels: codex

#14957 Align cost value totals in department stock report
  src/main/webapp/pharmacy/pharmacy_report_department_stock_by_batch_dto.xhtml
Labels: codex

#14961 feat: add GRN return approval workflow
  src/main/java/com/divudi/bean/common/BillSearch.java
  src/main/java/com/divudi/bean/common/ConfigOptionApplicationController.java
  src/main/java/com/divudi/bean/pharmacy/GrnReturnApprovalController.java
  src/main/webapp/pharmacy/pharmacy_grn_list_for_return.xhtml
  src/main/webapp/pharmacy/pharmacy_grn_return_approval.xhtml
  src/main/webapp/pharmacy/pharmacy_grn_return_request.xhtml
Labels: codex

#14962 Add pharmacy donation bill types
  src/main/java/com/divudi/core/data/BillType.java
  src/main/java/com/divudi/core/data/BillTypeAtomic.java
Labels: codex

#15005 fix: enable transporter lookup by staff code
  src/main/java/com/divudi/bean/hr/StaffController.java
Labels: codex

#15008 feat: add pharmacy donation menu item
  src/main/webapp/resources/ezcomp/menu.xhtml
Labels: codex

#15010 Use pharmacy_donation_receipt for donation previews and reprints
  src/main/webapp/pharmacy/donation.xhtml
  src/main/webapp/pharmacy/pharmacy_reprint_purchase.xhtml
Labels: codex

#14986 Direct Purchase Voucher #14966
  src/main/webapp/resources/pharmacy/purhcase.xhtml
Labels: Urgent, Pharmacy, COOP Hospital

#15049 14924 required excel button to check the selected data
  src/main/java/com/divudi/bean/common/CollectingCentrePaymentController.java
  src/main/webapp/collecting_centre/sent_payment_to_collecting_centre.xhtml
Labels: Ruhunu Hospital, Payment, Collecting Centres

#15050 Fixed - transaction-amount-required-in-payment-screen
  src/main/webapp/collecting_centre/sent_payment_to_collecting_centre.xhtml
Labels: Ruhunu Hospital, Payment, Collecting Centres

#15053 Consumption Report
  src/main/java/com/divudi/bean/pharmacy/PharmacyController.java
  src/main/java/com/divudi/core/data/DepartmentCategoryWiseItems.java
  src/main/webapp/reports/inventoryReports/consumption.xhtml
Labels: bug

#14990 Search families. #14138
  src/main/java/com/divudi/bean/common/PatientController.java
  src/main/webapp/membership/family_membership_search.xhtml
Labels: Membership, COOP Hospital

#15054 Expiry Item Report #14992
  src/main/java/com/divudi/bean/report/PharmacyReportController.java
  src/main/webapp/reports/inventoryReports/expiry_item.xhtml
Labels: bug

#15055 Fixed - for-cancellation-bills-reference-number-not-showing
  src/main/java/com/divudi/bean/common/CollectingCentrePaymentController.java
Labels: Ruhunu Hospital, Payment, Collecting Centres

#15061 feat: add item filtered purchase report
  developer_docs/navigation/item_wise_purchase_bill_view.md
  developer_docs/navigation/pharmacy_navigation.md
  src/main/java/com/divudi/bean/pharmacy/PharmacyPurchaseController.java
  src/main/java/com/divudi/core/data/dto/PharmacyItemPurchaseDTO.java
  src/main/webapp/pharmacy/report_item_vice_purchase_and_good_receive.xhtml
Labels: codex

#14878 14275 oncall cash booking is absent it is displayed twice in the patient absent report
  src/main/java/com/divudi/bean/channel/BookingControllerViewScope.java
  src/main/java/com/divudi/bean/channel/ChannelReportController.java
  src/main/webapp/channel/session_instance.xhtml
Labels: Channelling

#15078 docs: list pharmacy menu pages
  pharmacy_pages.txt
Labels: codex

#15103 14929 cancellation process need to develop reversal the payment
  src/main/java/com/divudi/bean/common/AgentAndCcApplicationController.java
  src/main/java/com/divudi/bean/common/CollectingCentrePaymentController.java
  src/main/java/com/divudi/core/data/BillType.java
  src/main/java/com/divudi/core/data/HistoryType.java
  src/main/webapp/collecting_centre/cc_payment_cancel.xhtml
  src/main/webapp/collecting_centre/cc_repayment_bill_reprint.xhtml
  src/main/webapp/collecting_centre/collecting_centre_repayment_bill_search.xhtml
Labels: Ruhunu Hospital, Payment

#15107 feat: add pharmacy stock management bill types
  src/main/java/com/divudi/core/data/BillTypeAtomic.java
Labels: codex

#15108 feat: add privilege for pharmacy physical count approval
  src/main/java/com/divudi/bean/common/UserPrivilageController.java
  src/main/java/com/divudi/core/data/Privileges.java
  src/main/webapp/pharmacy/pharmacy_variant_adjustment.xhtml
  src/main/webapp/pharmacy/pharmacy_variant_ajustment_pre_list_.xhtml
Labels: codex

#15110 feat: import pharmacy stock count sheets
  src/main/java/com/divudi/bean/pharmacy/PharmacyStockTakeController.java
  src/main/webapp/pharmacy/pharmacy_stock_take.xhtml
Labels: codex

#15111 feat: add stock take approval workflow
  src/main/java/com/divudi/bean/pharmacy/PharmacyStockTakeController.java
  src/main/java/com/divudi/core/data/Privileges.java
Labels: codex

#15112 feat: add stock adjustment variance report
  src/main/java/com/divudi/bean/pharmacy/PharmacyAdjustmentReportController.java
  src/main/java/com/divudi/bean/pharmacy/PharmacyController.java
  src/main/webapp/pharmacy/pharmacy_analytics.xhtml
  src/main/webapp/pharmacy/reports/stock_adjustment_variance.xhtml
Labels: codex

#15126 15125 - Improving Investigation Tracking History
  src/main/java/com/divudi/bean/lab/LabTestHistoryController.java
  src/main/java/com/divudi/bean/lab/PatientInvestigationController.java
  src/main/webapp/lab/lab_test_history.xhtml
  src/main/webapp/resources/css/lab-test-history.css
Labels: Urgent, Lab, Ruhunu Hospital

#15146 Add header fallback for pharmacy transfer request receipt
  src/main/webapp/resources/pharmacy/pharmacy_transfer_request_receipt.xhtml
Labels: codex

#15150 fix spellings change
  src/main/webapp/admin/items/opd_service_inactive.xhtml
Labels: Administration, Adjustment

#15158 fix spellings change
  src/main/webapp/admin/items/opd_service.xhtml
Labels: Administration, Adjustment

#15142 Search family members #15075
  src/main/java/com/divudi/bean/common/PatientController.java
Labels: Membership, COOP Hospital

#15162 15058 direct purchase bill settlement report item ordering
  src/main/java/com/divudi/bean/pharmacy/PharmacyBillSearch.java
  src/main/java/com/divudi/bean/report/PharmacyReportController.java
  src/main/webapp/pharmacy/direct_purchase_summery_report.xhtml
  src/main/webapp/pharmacy/pharmacy_analytics.xhtml
Labels: Pharmacy, Report, COOP Hospital

#15178 15177 restrict regenerating a sample that has already been regenerated
  src/main/java/com/divudi/bean/lab/PatientInvestigationController.java
  src/main/webapp/lab/generate_barcode_p.xhtml
Labels: Urgent, Lab, Ruhunu Hospital

#15185 15184 improving barcode regenerate process
  src/main/java/com/divudi/bean/lab/PatientInvestigationController.java
  src/main/java/com/divudi/core/data/lab/ListingEntity.java
  src/main/webapp/lab/generate_barcode_p.xhtml
Labels: Lab, Ruhunu Hospital

#15203 15201 - Update CC Bill Header phone Number Issue
  src/main/webapp/requests/ix.xhtml
  src/main/webapp/resources/bill/cc_bill/cc_five_five_custom_3.xhtml
  src/main/webapp/resources/bill/cc_bill/cc_five_five_custom_3_patient.xhtml
Labels: Southern Lanka Hospital, Collecting Centres

#15206 15205 update company name in project
  src/main/webapp/about_software.xhtml
  src/main/webapp/mobile/dl.xhtml
  src/main/webapp/resources/bill/grn_payment_with_pre_bill.xhtml
  src/main/webapp/resources/bill/posOpdBillAdvance.xhtml
  src/main/webapp/resources/ezcomp/bmsOnlinePayment.xhtml
  src/main/webapp/resources/ezcomp/prints/five_eight_opd_bill.xhtml
  src/main/webapp/resources/ezcomp/prints/five_eight_opd_bill_inward.xhtml
  src/main/webapp/resources/optician/saleBill_Header.xhtml
  src/main/webapp/resources/optician/saleBill_prabodha.xhtml
  src/main/webapp/resources/optician/saleBill_without_item.xhtml
  src/main/webapp/resources/pharmacy/saleBill_Header.xhtml
  src/main/webapp/resources/pharmacy/saleBill_Header_Cancel.xhtml
  src/main/webapp/resources/pharmacy/saleBill_Header_Inward.xhtml
  src/main/webapp/resources/pharmacy/saleBill_Header_Return.xhtml
  src/main/webapp/resources/pharmacy/saleBill_Header_Transfer.xhtml
  src/main/webapp/resources/pharmacy/saleBill_prabodha.xhtml
  src/main/webapp/resources/pharmacy/saleBill_prabodha_1.xhtml
  src/main/webapp/resources/pharmacy/saleBill_without_item.xhtml
  src/main/webapp/resources/store/saleBill.xhtml
  src/main/webapp/resources/template/template.xhtml
  src/main/webapp/resources/template/template_channeling_tab_view.xhtml
  src/main/webapp/resources/template/template_without_menu.xhtml
Labels: Code Improvement

#15208 Lab Income Report Print Preview #14967
  src/main/webapp/reportLab/laboratary_income_report_print.xhtml
Labels: Lab, Report, COOP Hospital

#15199 Pharmacy direct purchase report #15195
  src/main/webapp/pharmacy/direct_purchase_summery_report.xhtml
  src/main/webapp/pharmacy/direct_purchase_summery_report_print.xhtml
Labels: Pharmacy, Report, COOP Hospital

#15194 fix spellings change
  src/main/webapp/admin/items/inward_service.xhtml
Labels: Administration, Adjustment
