Repository hmislk/hmis, pull requests merged in 2025-07, with the labels that each got.

#13552 Add online settlement component
  src/main/java/com/divudi/bean/channel/BookingController.java
  src/main/java/com/divudi/bean/channel/BookingControllerViewScope.java
  src/main/java/com/divudi/bean/channel/BookingControllerViewScopeMonth.java
  src/main/java/com/divudi/bean/clinic/ClinicController.java
  src/main/java/com/divudi/bean/common/BillController.java
  src/main/java/com/divudi/bean/common/BillPackageController.java
  src/main/java/com/divudi/bean/common/OpdPreSettleController.java
  src/main/java/com/divudi/bean/opd/OpdBillController.java
  src/main/java/com/divudi/bean/opd/OpdOrderController.java
  src/main/java/com/divudi/core/data/dataStructure/PaymentMethodData.java
  src/main/java/com/divudi/service/PaymentService.java
Labels: codex

#13543 #13206 cogs grn credit
  src/main/webapp/reports/inventoryReports/grn_credit.xhtml
Labels: Report, Ruhunu Hospital

#13556 Add online payment section
  src/main/webapp/opd/opd_bill.xhtml
  src/main/webapp/opd/opd_bill_ac.xhtml
  src/main/webapp/resources/paymentMethod/online_settlement.xhtml
Labels: codex

#13557 Fix multi payment totals for online settlement
  src/main/java/com/divudi/bean/opd/OpdBillController.java
Labels: codex

#13562 Enable inline bill editing
  src/main/webapp/opd/view/bill_admin.xhtml
  src/main/webapp/opd/view/cc_deposit_bill_admin.xhtml
  src/main/webapp/opd/view/opd_bill_admin.xhtml
  src/main/webapp/opd/view/opd_cancellation_bill_admin.xhtml
  src/main/webapp/opd/view/opd_refund_bill_admin.xhtml
Labels: codex

#13567 Direct purchase return note #13190
  src/main/webapp/resources/pharmacy/direct_purchase_return_receipt_with_costing.xhtml
Labels: Urgent, Pharmacy, Ruhunu Hospital

#13574 13382 need improvements in agent channel booking report
  src/main/java/com/divudi/bean/channel/BookingControllerViewScope.java
  src/main/webapp/channel/agent_channel_bookings.xhtml
  src/main/webapp/channel/agent_channel_bookings_print.xhtml
  src/main/webapp/channel/channel_income.xhtml
  src/main/webapp/channel/channel_report_absent_patients.xhtml
Labels: Channelling

#12936 Rmh pharmacy reprint issue(do not merge) hotfix
  src/main/webapp/resources/pharmacy/returnBill.xhtml
Labels: RMH, Hot Fix

#13546 Add new opd bill number strategy for single bill hotfix
  src/main/java/com/divudi/bean/inward/BillBhtController.java
  src/main/java/com/divudi/bean/opd/OpdBillController.java
  src/main/java/com/divudi/core/data/BillTypeAtomic.java
  src/main/java/com/divudi/ejb/BillNumberGenerator.java
Labels: Lab, COOP Hospital, Hot Fix

#13580 #13566 cogs purchase return
  src/main/webapp/reports/inventoryReports/purchase_return.xhtml
Labels: Report, Ruhunu Hospital

#13590 #13572 cogs grn cash
  src/main/java/com/divudi/bean/report/PharmacyReportController.java
  src/main/webapp/reports/inventoryReports/grn_cash.xhtml
Labels: Report, Ruhunu Hospital

#13609 13607 enable direct result entry
  src/main/java/com/divudi/core/entity/lab/Investigation.java
  src/main/webapp/admin/lims/investigation.xhtml
  src/main/webapp/opd/opd_batch_bill_print.xhtml
Labels: codex

#13610 Add Bill DeptId bulk editor
  src/main/java/com/divudi/bean/common/BillDeptIdEditorController.java
  src/main/webapp/dataAdmin/admin_functions.xhtml
  src/main/webapp/dataAdmin/bill_deptid_editor.xhtml
Labels: codex

#13611 Add batch bill patient investigation lookup
  src/main/java/com/divudi/bean/common/BillSearch.java
  src/main/java/com/divudi/service/BillService.java
Labels: codex

#13618 Add Investigation DTO and extend developer view
  src/main/java/com/divudi/bean/lab/InvestigationController.java
  src/main/java/com/divudi/core/data/dto/InvestigationDTO.java
  src/main/webapp/admin/lims/developers/lab_investigation_list_for_developers.xhtml
Labels: codex

#13619 Add patient name capitalization options
  src/main/java/com/divudi/bean/common/ConfigOptionApplicationController.java
  src/main/java/com/divudi/bean/common/PatientController.java
  src/main/java/com/divudi/bean/inward/AdmissionController.java
Labels: codex

#13624 Handle pack items in transfer issue generation
  src/main/java/com/divudi/bean/pharmacy/TransferIssueController.java
Labels: codex

#13625 Fix history trigger for transfer issue
  src/main/webapp/pharmacy/pharmacy_transfer_issue.xhtml
Labels: codex

#13626 Implement audit tracking for bill dept ID updates
  src/main/java/com/divudi/bean/common/BillDeptIdEditorController.java
  src/main/webapp/audit/all_audit_events.xhtml
  src/main/webapp/dataAdmin/admin_data_administration.xhtml
Labels: codex

#13633 Add weekly VM restart scheduling script with SSH connectivity check
  .github/scripts/restart_servers_weekly.sh
Labels: enhancement

#13637 Add generics to params maps
  src/main/java/com/divudi/ejb/PharmacyBean.java
  src/main/java/com/divudi/service/BillService.java
Labels: codex

#13645 Add finalize transfer requests list
  src/main/java/com/divudi/bean/common/SearchController.java
  src/main/webapp/pharmacy/pharmacy_transfer_request_list_to_finalize.xhtml
  src/main/webapp/resources/ezcomp/menu.xhtml
Labels: codex

#13649 Add item history button to transfer request save page
  src/main/webapp/pharmacy/pharmacy_transfer_request_save.xhtml
Labels: codex

#13650 Implement transfer request bill item fetch
  src/main/java/com/divudi/bean/pharmacy/TransferRequestController.java
Labels: codex

#13646 Add Transfer Request finalization flow
  src/main/java/com/divudi/bean/pharmacy/TransferRequestController.java
  src/main/webapp/pharmacy/pharmacy_transfer_request_list_to_finalize.xhtml
  src/main/webapp/resources/ezcomp/menu.xhtml
Labels: codex

#13653 Fix duplicate items on transfer finalization
  src/main/java/com/divudi/bean/pharmacy/TransferRequestController.java
Labels: codex

#13654 Add rate calculations on transfer request page
  src/main/java/com/divudi/bean/pharmacy/TransferRequestController.java
  src/main/webapp/pharmacy/pharmacy_transfer_request.xhtml
Labels: codex

#13656 Enhance transfer request costing controls
  src/main/java/com/divudi/bean/pharmacy/TransferRequestController.java
  src/main/webapp/pharmacy/pharmacy_transfer_request.xhtml
Labels: codex

#13657 Add qty and rate recalculation
  src/main/java/com/divudi/bean/pharmacy/TransferRequestController.java
  src/main/webapp/pharmacy/pharmacy_transfer_request.xhtml
Labels: codex

#13660 show recent departments on transfer request page
  src/main/java/com/divudi/bean/pharmacy/TransferRequestController.java
  src/main/webapp/pharmacy/pharmacy_transfer_request.xhtml
Labels: codex

#13661 Bug fix: pharmacy transfer request totals
  src/main/java/com/divudi/bean/pharmacy/TransferRequestController.java
Labels: codex

#13643 #13421 cogs transfer receive
  src/main/java/com/divudi/bean/report/PharmacyReportController.java
  src/main/webapp/reports/inventoryReports/transfer_receive.xhtml
Labels: Report, Ruhunu Hospital

#13669 13668-enhance-login-flow-with-department-auto-selection-and-recent-department-quick-access
  src/main/java/com/divudi/bean/common/SessionController.java
  src/main/webapp/resources/ezcomp/select_department.xhtml
Labels: codex

#13672 Open GRN Report Excel and PDF issues #13671
  src/main/java/com/divudi/bean/pharmacy/PharmacyController.java
  src/main/java/com/divudi/core/data/reports/InventoryReports.java
  src/main/webapp/reports/inventoryReports/grn_report.xhtml
Labels: bug

#13674 Implement ExternalImage support in lab reports
  src/main/java/com/divudi/core/data/InvestigationItemType.java
  src/main/java/com/divudi/ejb/PatientReportBean.java
  src/main/webapp/collecting_centre/courier/patient_report_print.xhtml
  src/main/webapp/lab/patient_report_print.xhtml
  src/main/webapp/requests/report.xhtml
  src/main/webapp/resources/ezcomp/lab/general_patient_report.xhtml
Labels: codex

#13681 11966-selectivey-render-pharmacy-reports
  README.md
  src/main/java/com/divudi/bean/common/ConfigOptionApplicationController.java
  src/main/webapp/pharmacy/pharmacy_analytics.xhtml
Labels: codex

#13682 Remove stray stackdump
  .gitignore
  sh.exe.stackdump
Labels: codex

#13684 11966-selectivey-render-pharmacy-reports
  README.md
  src/main/java/com/divudi/bean/common/ConfigOptionApplicationController.java
  src/main/webapp/pharmacy/pharmacy_analytics.xhtml
Labels: codex

#13686 Fix transfer request bill numbering
  src/main/java/com/divudi/bean/pharmacy/TransferRequestController.java
Labels: codex

#13694 Add range filters for report values
  src/main/java/com/divudi/bean/lab/PatientInvestigationController.java
  src/main/webapp/lab/clinical_result_values.xhtml
Labels: codex

#13695 Improve lab data loading and update efficiency
  src/main/java/com/divudi/bean/lab/PatientReportController.java
  src/main/webapp/lab/sample_management.xhtml
Labels: codex

#13693 Standardize home icons
  src/main/webapp/home.xhtml
  src/main/webapp/resources/images/home/add-patient-color.svg
  src/main/webapp/resources/images/home/add-patient.svg
  src/main/webapp/resources/images/home/addPatient.svg
  src/main/webapp/resources/images/home/addstock.svg
  src/main/webapp/resources/images/home/adjustment.svg
  src/main/webapp/resources/images/home/admissions-search.svg
  src/main/webapp/resources/images/home/analytics.svg
  src/main/webapp/resources/images/home/appointments.svg
  src/main/webapp/resources/images/home/bill-aprove-1.svg
  src/main/webapp/resources/images/home/bill-bprove.svg
  src/main/webapp/resources/images/home/bill.svg
  src/main/webapp/resources/images/home/bill1.svg
  src/main/webapp/resources/images/home/bill_aprove_1.svg
  src/main/webapp/resources/images/home/bill_bprove.svg
  src/main/webapp/resources/images/home/cashier-drawer.svg
  src/main/webapp/resources/images/home/cashier.svg
  src/main/webapp/resources/images/home/channel-booking-by-dates.svg
  src/main/webapp/resources/images/home/channel-scheduling.svg
  src/main/webapp/resources/images/home/direct-purchase.svg
  src/main/webapp/resources/images/home/financial-transaction-manager.svg
  src/main/webapp/resources/images/home/health-worker-form.svg
  src/main/webapp/resources/images/home/hospital.svg
  src/main/webapp/resources/images/home/in.svg
  src/main/webapp/resources/images/home/investigation-trace.svg
  src/main/webapp/resources/images/home/invoice.svg
  src/main/webapp/resources/images/home/lab-report.svg
  src/main/webapp/resources/images/home/lab_report.svg
  src/main/webapp/resources/images/home/opd-default.svg
  src/main/webapp/resources/images/home/out.svg
  src/main/webapp/resources/images/home/payment(1).svg
  src/main/webapp/resources/images/home/payment-1.svg
  src/main/webapp/resources/images/home/payment.svg
  src/main/webapp/resources/images/home/pharmacy-analytics.svg
  src/main/webapp/resources/images/home/pharmacy-default.svg
  src/main/webapp/resources/images/home/pharmacy_default.svg
  src/main/webapp/resources/images/home/profile.svg
  src/main/webapp/resources/images/home/re-payment.svg
  src/main/webapp/resources/images/home/refund.svg
  src/main/webapp/resources/images/home/refund1.svg
  src/main/webapp/resources/images/home/reports.svg
  src/main/webapp/resources/images/home/scan.svg
  src/main/webapp/resources/images/home/search-patient.svg
  src/main/webapp/resources/images/home/search_patient.svg
  src/main/webapp/resources/images/home/summary-report.svg
  src/main/webapp/resources/images/home/summary_report.svg
  src/main/webapp/resources/images/home/supplier-payment-management.svg
  src/main/webapp/resources/images/home/supplier-payment.svg
  src/main/webapp/resources/images/home/times.svg
  src/main/webapp/resources/images/home/token.svg
  src/main/webapp/resources/images/home/transfer.svg
Labels: codex

#13700 13698 add report execution log capturing to lab dashboard
  src/main/java/com/divudi/bean/common/ReportTimerController.java
  src/main/java/com/divudi/bean/lab/LaboratoryManagementController.java
  src/main/java/com/divudi/core/data/reports/CommonReports.java
  src/main/java/com/divudi/core/entity/report/ReportLog.java
  src/main/webapp/dataAdmin/report_execution_logs.xhtml
Labels: codex

#13702 Refactor report timer tracking method
  src/main/java/com/divudi/bean/common/ReportTimerController.java
Labels: codex

#13711 Signed-off-by: Lawan Samarasekara <lawan.chaamindu1234@gmail.com>
  src/main/webapp/inward/inward_bill_service.xhtml
Labels: Hot Fix

#13713 13710 refactor lab dashboard logging
  src/main/java/com/divudi/bean/common/ReportTimerController.java
  src/main/java/com/divudi/bean/lab/LaboratoryManagementController.java
Labels: codex

#13715 Fix ampersand text in pharmacy analytics
  src/main/webapp/pharmacy/pharmacy_analytics.xhtml
Labels: codex

#13716 Enhance transfer issue editing
  src/main/java/com/divudi/bean/pharmacy/TransferIssueController.java
  src/main/webapp/pharmacy/pharmacy_transfer_issue.xhtml
Labels: codex

#13722 13721 list patients by area
  src/main/webapp/admin/users/send_bulk_sms_patients.xhtml
Labels: codex

#13724 Fix zero quantity items in transfer issue
  src/main/java/com/divudi/bean/pharmacy/TransferIssueController.java
Labels: codex

#13726 Fix transfer issue totals
  src/main/webapp/pharmacy/pharmacy_transfer_issue.xhtml
Labels: codex

#13731 SLH Pharmacy income report
  src/main/java/com/divudi/bean/common/BillSearch.java
  src/main/java/com/divudi/bean/pharmacy/PharmacySummaryReportController.java
  src/main/java/com/divudi/core/data/IncomeBundle.java
  src/main/java/com/divudi/core/data/IncomeRow.java
  src/main/java/com/divudi/core/data/dto/PharmacyIncomeBillDTO.java
  src/main/java/com/divudi/service/BillService.java
  src/main/webapp/pharmacy/reports/summary_reports/pharmacy_income_report.xhtml
Labels: bug

#13735 fix negative qty when creating transfer receive
  src/main/java/com/divudi/bean/pharmacy/TransferReceiveController.java
Labels: codex

#13739 Fix receive bill rebuild when reopening issue
  src/main/java/com/divudi/bean/pharmacy/TransferReceiveController.java
Labels: codex

#13767 12875-incorrect-grn-billitem-quantity-ampp
  src/main/java/com/divudi/bean/pharmacy/GrnCostingController.java
Labels: codex

#13779 Modify UserIcon form handling
  src/main/java/com/divudi/bean/common/UserIconController.java
  src/main/webapp/admin/users/user_icons.xhtml
Labels: codex

#13781 Add details to stock history quantities tab
  src/main/webapp/analytics/pharmacy/stock_history.xhtml
Labels: codex

#13798 Implement GRN return with costing
  src/main/java/com/divudi/bean/common/BillSearch.java
  src/main/java/com/divudi/bean/pharmacy/GrnReturnWithCostingController.java
  src/main/webapp/pharmacy/grn_return_with_costing.xhtml
  src/main/webapp/pharmacy/pharmacy_grn_list_for_return.xhtml
  src/main/webapp/resources/pharmacy/grn_return_receipt_with_costing.xhtml
Labels: codex

#13800 Update BHT Issue Requests link
  src/main/webapp/home.xhtml
Labels: codex

#13802 Add finalize purchase order icon
  src/main/java/com/divudi/core/data/Icon.java
  src/main/webapp/home.xhtml
  src/main/webapp/resources/images/home/purchase-order-finalize.svg
Labels: codex

#13803 Add finance details tabs to bill admin view
  src/main/webapp/opd/view/bill_admin.xhtml
Labels: codex

#13806 Add extra details to pharmaceutical item list
  src/main/webapp/resources/ezcomp/view/pharmaceutical_bill_item_list_edit.xhtml
Labels: codex

#13808 Add bill item finance details inside bill items tab
  src/main/webapp/opd/view/bill_admin.xhtml
Labels: codex

#13809 Implement generic bill JSON export
  src/main/java/com/divudi/service/BillService.java
Labels: codex

#13811 Handle costing-based direct purchase navigation
  src/main/webapp/home.xhtml
Labels: codex

#13813 Need to improve CC Bill item list calendar #13789
  src/main/webapp/reports/collectionCenterReports/cc_bill_item_list.xhtml
Labels: bug

#13820 Fix GRN return quantity calculations
  src/main/java/com/divudi/bean/pharmacy/GrnReturnWithCostingController.java
  src/main/java/com/divudi/service/pharmacy/PharmacyCostingService.java
Labels: codex

#13828 Fix missing editable toggles in bill_edit.xhtml
  src/main/webapp/resources/ezcomp/view/bill_edit.xhtml
Labels: codex

#13834 13824-fix-incorrect-column-span-calculation-in-grn-return-receipt-footer
  src/main/webapp/resources/pharmacy/grn_return_receipt_with_costing.xhtml
Labels: codex

#13836 Fix bug in total quantity and remove debug prints
  src/main/java/com/divudi/service/pharmacy/PharmacyCostingService.java
Labels: codex

#13840 13830-add-null-safety-checks-in-pharmacycostingservice-addpharmaceuticalbillitemquantitiesfrombillitemfinancedetailquantities
  src/main/java/com/divudi/service/pharmacy/PharmacyCostingService.java
Labels: codex

#13844 Fix typo in PharmacyCostingService method names
  src/main/java/com/divudi/bean/pharmacy/GrnReturnWithCostingController.java
  src/main/java/com/divudi/service/pharmacy/PharmacyCostingService.java
Labels: codex

#13848 Fix division by zero in PharmacyCostingService
  src/main/java/com/divudi/service/pharmacy/PharmacyCostingService.java
Labels: codex

#13856 Add edit workflow for AMPP management
  src/main/java/com/divudi/bean/pharmacy/AmppController.java
  src/main/webapp/pharmacy/admin/ampp.xhtml
Labels: codex

#13858 Fix already returned quantity display in GRN return with costing
  src/main/java/com/divudi/bean/pharmacy/GrnReturnWithCostingController.java
Labels: codex

#13861 Implement editable modes for pharmacy controllers
  src/main/java/com/divudi/bean/pharmacy/AmpController.java
  src/main/java/com/divudi/bean/pharmacy/AtmController.java
  src/main/java/com/divudi/bean/pharmacy/VmpController.java
  src/main/java/com/divudi/bean/pharmacy/VmppController.java
  src/main/java/com/divudi/bean/pharmacy/VtmController.java
  src/main/webapp/pharmacy/admin/atm.xhtml
  src/main/webapp/pharmacy/admin/vtm.xhtml
Labels: codex

#13862 Fix already returned quantity display in GRN return with costing
  src/main/java/com/divudi/bean/pharmacy/GrnReturnWithCostingController.java
Labels: codex

#13864 Fix item fee setter for foreigners
  src/main/java/com/divudi/service/ItemFeeService.java
Labels: codex

#13867 Add Excel parsing for department fees
  src/main/java/com/divudi/bean/common/ItemController.java
Labels: codex

#13873 13872-remove-unused-parsedepartmentfeesfromexcel-method-in-itemcontroller
  src/main/java/com/divudi/bean/common/ItemController.java
Labels: codex

#13860 Fix already returned quantity display in GRN return with costing
  src/main/java/com/divudi/bean/pharmacy/GrnReturnWithCostingController.java
Labels: codex

#13875 Fix GRN return bill item calculation
  src/main/java/com/divudi/bean/pharmacy/GrnReturnWithCostingController.java
Labels: codex

#13876 Fix duplicate list initialization
  src/main/java/com/divudi/bean/common/ItemController.java
Labels: codex

#13878 Populate return item costing fields
  src/main/java/com/divudi/bean/pharmacy/GrnReturnWithCostingController.java
Labels: codex

#13879 Fix incorrect success message in addNewForSiteFee
  src/main/java/com/divudi/bean/common/ItemFeeManager.java
Labels: codex

#13881 Fix issue 13869
  src/main/java/com/divudi/bean/common/BillBeanController.java
Labels: codex

#13884 Fix GRN return finance totals
  src/main/java/com/divudi/bean/pharmacy/GrnReturnWithCostingController.java
Labels: codex

#13886 Resolve debug output and clarify new fee methods
  src/main/java/com/divudi/bean/common/BillBeanController.java
  src/main/java/com/divudi/bean/common/OpdPreBillController.java
  src/main/java/com/divudi/bean/opd/OpdBillController.java
  src/main/java/com/divudi/bean/opd/OpdOrderController.java
Labels: codex

#13887 Add department field to payment scheme page
  src/main/java/com/divudi/core/entity/PaymentScheme.java
  src/main/webapp/admin/pricing/payment_scheme.xhtml
Labels: codex

#13890 Improve PaymentScheme duplication transaction handling
  src/main/java/com/divudi/bean/membership/PaymentSchemeController.java
Labels: codex

#13891 Fix duplicate payment scheme page
  src/main/webapp/admin/pricing/membership/payment_scheme.xhtml
  src/main/webapp/admin_fees.xhtml
Labels: codex

#13708 Signed-off-by: Lawan Samarasekara <lawan.chaamindu1234@gmail.com>
  src/main/java/com/divudi/bean/inward/AdmissionController.java
Labels: Hot Fix

#13733 Clearing previously entered phone number in OPD billing when adding a new bill-hotfix (Do not merge)
  src/main/java/com/divudi/bean/opd/OpdBillController.java
Labels: Hot Fix

#13899 Added report image to view report print page hotfix
  src/main/java/com/divudi/bean/lab/PatientReportController.java
  src/main/webapp/collecting_centre/courier/patient_report_print.xhtml
  src/main/webapp/lab/patient_report_print.xhtml
  src/main/webapp/requests/ix.xhtml
Labels: Lab, Hot Fix

#13897 13892 improving laboratory dashboard sample section
  src/main/java/com/divudi/bean/common/BillSearch.java
  src/main/java/com/divudi/bean/lab/LaboratoryManagementController.java
  src/main/java/com/divudi/bean/lab/PatientInvestigationController.java
  src/main/java/com/divudi/bean/opd/OpdBillController.java
  src/main/webapp/admin/lims/investigation.xhtml
  src/main/webapp/inward/inward_bill_service.xhtml
  src/main/webapp/inward/inward_cancel_bill_service.xhtml
  src/main/webapp/inward/inward_reprint_bill_service.xhtml
  src/main/webapp/lab/patient_report_without_sample_sending_process.xhtml
  src/main/webapp/opd/opd_batch_bill_print.xhtml
  src/main/webapp/resources/ezcomp/lab/dashboard/patient_sample.xhtml
  src/main/webapp/resources/ezcomp/prints/five_eight_opd_bill_inward.xhtml
Labels: Laboratory Dashboard

#13926 Add batch details on transfer issue receipt
  src/main/webapp/resources/pharmacy/pharmacy_transfer_issue_receipt.xhtml
Labels: codex

#13938 Add All Item Movement Summary report page
  src/main/java/com/divudi/bean/pharmacy/PharmacySummaryReportController.java
  src/main/webapp/pharmacy/pharmacy_analytics.xhtml
  src/main/webapp/pharmacy/reports/summary_reports/all_item_movement_summary.xhtml
Labels: codex

#13940 Fix transfer receive receipt
  src/main/java/com/divudi/bean/common/ConfigOptionApplicationController.java
  src/main/webapp/resources/pharmacy/pharmacy_transfer_receive_receipt.xhtml
Labels: codex

#13942 Add defaults for transfer receive receipts
  src/main/java/com/divudi/bean/common/ConfigOptionApplicationController.java
Labels: codex

#13943 Implement all item movement async report
  src/main/java/com/divudi/bean/pharmacy/PharmacySummaryReportController.java
  src/main/java/com/divudi/service/PharmacyAsyncReportService.java
Labels: codex

#13945 Add download option for async excel
  src/main/java/com/divudi/bean/pharmacy/PharmacySummaryReportController.java
  src/main/webapp/pharmacy/reports/summary_reports/all_item_movement_summary.xhtml
Labels: codex

#13946 Use DTO for item movement summary report
  src/main/java/com/divudi/core/data/dto/ItemMovementSummaryDTO.java
  src/main/java/com/divudi/core/facade/PharmaceuticalBillItemFacade.java
  src/main/java/com/divudi/service/BillService.java
  src/main/java/com/divudi/service/PharmacyAsyncReportService.java
Labels: codex

#13949 Fix equality checks when fetching summary report history
  src/main/java/com/divudi/bean/pharmacy/PharmacySummaryReportController.java
Labels: codex

#13951 Add stock retrieval service methods
  src/main/java/com/divudi/bean/pharmacy/StockController.java
  src/main/java/com/divudi/service/StockService.java
Labels: codex

#13952 Improve item movement report columns
  src/main/java/com/divudi/service/PharmacyAsyncReportService.java
Labels: codex

#13960 Fix totals row in item movement report
  src/main/java/com/divudi/service/PharmacyAsyncReportService.java
Labels: codex

#13969 Transfer issue note cancelled #11164
  src/main/webapp/pharmacy/pharmacy_reprint_bill_unit_issue.xhtml
  src/main/webapp/resources/pharmacy/transferIssue.xhtml
Labels: Pharmacy

#13978 13974 improvements in channel absent report
  src/main/java/com/divudi/bean/channel/BookingControllerViewScope.java
  src/main/java/com/divudi/service/ChannelService.java
  src/main/webapp/channel/channel_booking.xhtml
  src/main/webapp/channel/channel_payment_staff_bill.xhtml
  src/main/webapp/channel/channel_report_absent_patients.xhtml
  src/main/webapp/channel/session_instance.xhtml
Labels: Channelling

#13983 Refactor return bill calculations to correctly set totals,
  src/main/java/com/divudi/bean/pharmacy/PharmacySummaryReportController.java
  src/main/java/com/divudi/bean/pharmacy/PreReturnController.java
Labels: bug

#13989 Add methods to complete items with retired status
  src/main/java/com/divudi/bean/common/ItemController.java
  src/main/java/com/divudi/bean/pharmacy/AmpController.java
Labels: bug

#14003 14001 upgrade pharmacy item import without stock to support optional department type column
  src/main/java/com/divudi/bean/emr/DataUploadController.java
  src/main/webapp/pharmacy/pharmacy_item_import_without_stock.xhtml
Labels: codex

#14015 Add department-aware pharmacy item completion
  src/main/java/com/divudi/bean/common/ItemController.java
  src/main/webapp/pharmacy/direct_purchase.xhtml
  src/main/webapp/pharmacy/pharmacy_purchase.xhtml
  src/main/webapp/pharmacy/pharmacy_transfer_request.xhtml
Labels: codex

#14016 Add stock autocomplete filter for allowed department types
  src/main/java/com/divudi/bean/pharmacy/StockController.java
  src/main/webapp/pharmacy/pharmacy_issue.xhtml
  src/main/webapp/pharmacy/pharmacy_transfer_issue_direct_department.xhtml
Labels: codex

#14025 Fix Amp JPQL queries in lab controller
  src/main/java/com/divudi/bean/lab/LabAmpController.java
Labels: codex

#14047 Implement optimized pharmacy retail sale page
  src/main/java/com/divudi/bean/pharmacy/PharmacyFastRetailSaleController.java
  src/main/java/com/divudi/core/data/Privileges.java
  src/main/webapp/pharmacy/pharmacy_fast_retail_sale.xhtml
  src/main/webapp/resources/ezcomp/menu.xhtml
Labels: codex

#14060 Allow saving zero-value fees
  src/main/java/com/divudi/bean/common/ItemFeeManager.java
Labels: codex

#14069 Speed up fast retail autocomplete
  src/main/java/com/divudi/bean/pharmacy/PharmacyFastRetailSaleController.java
  src/main/java/com/divudi/core/data/dto/StockDTO.java
  src/main/webapp/pharmacy/pharmacy_fast_retail_sale.xhtml
Labels: codex

#14028 #13720 cogs transfer receive
  src/main/webapp/reports/inventoryReports/transfer_receive.xhtml
Labels: Report

#14045 Pharmacy transfer request #13980
  src/main/java/com/divudi/bean/pharmacy/TransferRequestController.java
  src/main/webapp/pharmacy/pharmacy_transfer_request.xhtml
  src/main/webapp/resources/pharmacy/pharmacy_transfer_request_receipt.xhtml
Labels: Urgent, Pharmacy, Ruhunu Hospital

#14072 Transfer Receive Note #13982
  src/main/webapp/resources/pharmacy/transferReceive.xhtml
Labels: Urgent, Pharmacy, Ruhunu Hospital

#14104 Fix payment amount override in PaymentProcessingService
  src/main/java/com/divudi/service/pharmacy/PaymentProcessingService.java
Labels: codex

#14073 GRN Return bill #13598
  src/main/webapp/resources/pharmacy/grnReturn.xhtml
Labels: Urgent, Pharmacy, Ruhunu Hospital

#14090 PO bill #13596
  src/main/webapp/resources/pharmacy/po.xhtml
Labels: Urgent, Pharmacy, Ruhunu Hospital

#14091 #14042_cogs_sale_credit_card
  src/main/java/com/divudi/bean/report/PharmacyReportController.java
Labels: Report, Ruhunu Hospital

#14108 Add expiry and sale value columns to non moving report
  src/main/webapp/pharmacy/pharmacy_report_department_non_moving.xhtml
  src/main/webapp/pharmacy/pharmacy_report_department_non_moving_print.xhtml
Labels: codex

#14115 Fix NullPointerException in PharmacyCalculation
  src/main/java/com/divudi/ejb/PharmacyCalculation.java
  src/test/java/com/divudi/ejb/PharmacyCalculationTest.java
Labels: codex

#14120 Add email sending for purchase orders
  src/main/java/com/divudi/bean/pharmacy/PurchaseOrderRequestController.java
  src/main/webapp/pharmacy/pharmacy_purhcase_order_request.xhtml
Labels: codex

#14153 Refactor payment creation for fast retail sales
  src/main/java/com/divudi/bean/pharmacy/PharmacyFastRetailSaleController.java
Labels: codex

#14154 Fix compile errors in debug logs and update bill finance details
  src/main/java/com/divudi/bean/pharmacy/PharmacySaleController.java
  src/main/java/com/divudi/bean/pharmacy/PharmacySummaryReportController.java
Labels: codex

#14166 GRN Report #14088 #13920
  src/main/webapp/resources/pharmacy/grn.xhtml
Labels: bug

#14174 Implement multi-batch purchase rate adjustments
  src/main/java/com/divudi/bean/pharmacy/PharmacyAdjustmentController.java
  src/main/java/com/divudi/core/data/dto/StockDTO.java
  src/main/webapp/pharmacy/adjustments/pharmacy_adjustment_purchase_rate.xhtml
Labels: codex

#14175 Enhance purchase rate adjustment printout
  db/migration/03_add_adjustment_totals.sql
  src/main/java/com/divudi/bean/pharmacy/PharmacyAdjustmentController.java
  src/main/java/com/divudi/core/entity/BillFinanceDetails.java
  src/main/webapp/resources/pharmacy/adjustmentBill_purchase_price.xhtml
Labels: codex

#14187 Fix for issue #14181
  src/main/java/com/divudi/bean/pharmacy/PharmacyAdjustmentController.java
  src/main/java/com/divudi/core/data/dto/StockDTO.java
  src/main/java/com/divudi/service/pharmacy/StockSearchService.java
  src/main/webapp/pharmacy/adjustments/pharmacy_adjustment_retail_sale_rate.xhtml
  src/main/webapp/resources/pharmacy/adjustmentBill_sale_price.xhtml
Labels: codex

#14186 14185 optimize stock deduction
  src/main/java/com/divudi/bean/pharmacy/PharmacyFastRetailSaleController.java
  src/main/java/com/divudi/ejb/OptimizedPharmacyBean.java
  src/test/java/com/divudi/ejb/OptimizedPharmacyBeanTest.java
Labels: codex

#14191 Implement pharmacy cost rate adjustment
  src/main/java/com/divudi/bean/pharmacy/PharmacyAdjustmentController.java
  src/main/java/com/divudi/core/data/BillType.java
  src/main/java/com/divudi/core/data/Privileges.java
  src/main/java/com/divudi/core/data/dto/StockDTO.java
  src/main/java/com/divudi/service/pharmacy/StockSearchService.java
  src/main/webapp/pharmacy/adjustments/pharmacy_adjustment_cost_rate.xhtml
  src/main/webapp/resources/pharmacy/adjustmentBill_cost_rate.xhtml
Labels: codex

#14227 Add reports navigation documentation
  developer_docs/navigation/reports_navigation.md
Labels: codex

#14226 14213 create lab navigation docs
  developer_docs/navigation/lab_navigation.md
Labels: codex

#14228 14212 create navigation documentation for pharmacy menu include page access paths privileges and config requirements
  developer_docs/navigation/pharmacy_navigation.md
Labels: codex

#14229 14215 channelling docs
  developer_docs/navigation/channelling_navigation.md
Labels: codex

#14231 Add developer docs README
  developer_docs/README.md
Labels: codex

#14232 Add channelling navigation guide
  developer_docs/navigation/channelling_navigation.md
Labels: codex

#14233 Add pharmacy navigation guide
  developer_docs/navigation/pharmacy_navigation.md
Labels: codex

#14235 Add channelling navigation guide
  developer_docs/navigation/channelling_navigation.md
Labels: codex

#14245 Add configuration-based navigation system for report optimization
  REPORT_OPTIMIZATION_IMPLEMENTATION_GUIDE.md
  src/main/java/com/divudi/core/data/dto/PharmacyIncomeReportDTO.java
  src/main/webapp/pharmacy/reports/summary_reports/pharmacy_income_report.xhtml
  src/main/webapp/pharmacy/reports/summary_reports/pharmacy_income_report_dto.xhtml
Labels: enhancement

#14254 Fix site filtering for JPQL queries
  src/main/java/com/divudi/bean/common/SearchController.java
  src/main/java/com/divudi/bean/opd/OpdReportController.java
  src/main/java/com/divudi/bean/pharmacy/PharmacySummaryReportController.java
Labels: codex

#14255 14220 optimize laboratory income report using dtos
  src/main/java/com/divudi/bean/common/ConfigOptionApplicationController.java
  src/main/java/com/divudi/bean/lab/LaborataryReportController.java
  src/main/java/com/divudi/core/data/dto/LabIncomeReportDTO.java
  src/main/java/com/divudi/service/BillService.java
  src/main/webapp/reportLab/laboratary_income_report.xhtml
  src/main/webapp/reportLab/laboratary_income_report_dto.xhtml
Labels: codex

#14262 Fix validation & layout in lab summary form
  src/main/webapp/reportLab/lab_daily_summary_by_department_dto.xhtml
Labels: codex

#14276 Fix DTO transfer issue report
  src/main/java/com/divudi/bean/pharmacy/ReportsTransfer.java
  src/main/webapp/pharmacy/reports/disbursement_reports/pharmacy_report_transfer_issue_bill_dto_print.xhtml
Labels: codex

#14282 Laboratory Card Income Report #14270
  src/main/webapp/reportLab/laboratary_card_income_report_print.xhtml
Labels: Urgent, Lab, Report

#14288 Channel Reports #14271
  src/main/webapp/channel/channel_reports.xhtml
Labels: Urgent, Channelling, Report, COOP Hospital
