Repository hmislk/hmis, pull requests merged in 2025-06, with the labels that each got.

#12700 Collection Center Book Wise Detail #12684
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/webapp/reports/collectionCenterReports/collection_centre_book_wise_detail.xhtml
Labels: bug

#12733 Opd and inward due report #12720
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/java/com/divudi/core/data/reports/FinancialReport.java
Labels: bug

#12737 PDF Totals issue fix
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/java/com/divudi/core/data/reports/FinancialReport.java
Labels: bug

#12740 Added a common header to debtor balance report
  src/main/webapp/reports/financialReports/debtor_balance_report.xhtml
Labels: bug

#12751 Move revenue count logic to BillService
  src/main/java/com/divudi/bean/report/PharmacySaleReportController.java
  src/main/java/com/divudi/ejb/BillReportBean.java
  src/main/java/com/divudi/service/BillService.java
Labels: codex

#12752 Add Maven install instructions
  INSTALL_GUIDE.md
Labels: codex

#12778 Fix null handling in JsfUtil
  src/main/java/com/divudi/core/util/JsfUtil.java
Labels: codex

#12779 Clarify staff salary comment
  src/main/java/com/divudi/bean/hr/StaffSalaryController.java
Labels: codex

#12780 Add numeric checks for CommonFunctions
  src/test/java/com/divudi/core/util/CommonFunctionsTest.java
Labels: codex

#12784 Update Maven compiler plugin for offline build
  pom.xml
Labels: codex

#12794 Add Appointments icon
  src/main/java/com/divudi/core/data/Icon.java
  src/main/webapp/home.xhtml
  src/main/webapp/resources/image/home/appointments.svg
Labels: codex

#12799 Add page listing all GRNs for supplier payments
  src/main/java/com/divudi/bean/pharmacy/SupplierPaymentController.java
  src/main/webapp/dealerPayment/index.xhtml
  src/main/webapp/dealerPayment/list_all_grns.xhtml
Labels: codex

#12802 Add icons for Admissions search and Investigations trace
  src/main/java/com/divudi/core/data/Icon.java
  src/main/webapp/home.xhtml
  src/main/webapp/resources/ezcomp/menu.xhtml
Labels: codex

#12804 Add user icons for inpatient search features
  AGENTS.md
  src/main/java/com/divudi/core/data/Icon.java
  src/main/resources/META-INF/persistence.xml
  src/main/webapp/home.xhtml
  src/main/webapp/resources/image/home/admissions_search.svg
  src/main/webapp/resources/image/home/investigation_trace.svg
Labels: codex

#12809 Add icons to stores menu
  AGENTS.md
  src/main/webapp/resources/ezcomp/menu.xhtml
Labels: codex

#12815 Add icons for pharmacy menu
  src/main/webapp/resources/ezcomp/menu.xhtml
  src/main/webapp/resources/ezcomp/pharmacyMenu.xhtml
Labels: codex

#12818 Replace bitmap icons with SVGs
  src/main/webapp/home.xhtml
  src/main/webapp/resources/image/home/direct_purchase.webp
  src/main/webapp/resources/image/home/grn.webp
  src/main/webapp/resources/image/home/pharmacy_analytics.png
  src/main/webapp/resources/image/home/supplier_payment.png
  src/main/webapp/resources/image/home/supplier_payment_management.webp
  src/main/webapp/resources/images/home/direct_purchase.svg
  src/main/webapp/resources/images/home/grn.svg
  src/main/webapp/resources/images/home/pharmacy_analytics.svg
  src/main/webapp/resources/images/home/supplier_payment_management.svg
Labels: codex

#12821 Relocate home icons
  src/main/webapp/home.xhtml
  src/main/webapp/resources/images/home/OPD_Default.svg
  src/main/webapp/resources/images/home/addPatient.svg
  src/main/webapp/resources/images/home/addPatient_color.svg
  src/main/webapp/resources/images/home/addstock.svg
  src/main/webapp/resources/images/home/adjustment.svg
  src/main/webapp/resources/images/home/admissions_search.svg
  src/main/webapp/resources/images/home/analytics.svg
  src/main/webapp/resources/images/home/appointments.svg
  src/main/webapp/resources/images/home/ban-solid.svg
  src/main/webapp/resources/images/home/bill.svg
  src/main/webapp/resources/images/home/bill1.svg
  src/main/webapp/resources/images/home/bill_aprove_1.svg
  src/main/webapp/resources/images/home/bill_bprove.svg
  src/main/webapp/resources/images/home/cart-shopping-solid.svg
  src/main/webapp/resources/images/home/cashier.svg
  src/main/webapp/resources/images/home/cashier_drawer.svg
  src/main/webapp/resources/images/home/health_worker_form.svg
  src/main/webapp/resources/images/home/hospital.svg
  src/main/webapp/resources/images/home/in.svg
  src/main/webapp/resources/images/home/investigation_trace.svg
  src/main/webapp/resources/images/home/invoice.svg
  src/main/webapp/resources/images/home/lab_report.svg
  src/main/webapp/resources/images/home/out.svg
  src/main/webapp/resources/images/home/payment(1).svg
  src/main/webapp/resources/images/home/payment.svg
  src/main/webapp/resources/images/home/pharmacy_default.svg
  src/main/webapp/resources/images/home/profile.svg
  src/main/webapp/resources/images/home/re_payment.svg
  src/main/webapp/resources/images/home/refund.svg
  src/main/webapp/resources/images/home/refund1.svg
  src/main/webapp/resources/images/home/reports.svg
  src/main/webapp/resources/images/home/sack-dollar-solid.svg
  src/main/webapp/resources/images/home/scan.svg
  src/main/webapp/resources/images/home/search.svg
  src/main/webapp/resources/images/home/search_patient.svg
  src/main/webapp/resources/images/home/summary_report.svg
  src/main/webapp/resources/images/home/supplier_payment.svg
  src/main/webapp/resources/images/home/times.svg
  src/main/webapp/resources/images/home/token.svg
  src/main/webapp/resources/images/home/transfer.svg
  src/main/webapp/resources/images/home/truck-solid.svg
Labels: codex

#12825 Add ManageCreditCompany privilege
  src/main/java/com/divudi/bean/common/UserPrivilageController.java
  src/main/java/com/divudi/core/data/Privileges.java
  src/main/webapp/admin/institutions/admin_institutions_index.xhtml
  src/main/webapp/admin/institutions/credit_company.xhtml
Labels: codex

#12829 Allow developer agentless report
  src/main/java/com/divudi/bean/common/ReportsController.java
Labels: codex

#12833 Fix collecting-centre bill validation
  src/main/java/com/divudi/service/BillService.java
Labels: codex

#12834 Add fee total mismatch checks
  src/main/java/com/divudi/service/BillService.java
Labels: codex

#12842 Add code generator and duplicate check for AMP
  src/main/java/com/divudi/bean/pharmacy/AmpController.java
  src/main/webapp/pharmacy/admin/amp.xhtml
Labels: codex

#12859 Add icons for lab menu
  src/main/webapp/resources/ezcomp/menu.xhtml
Labels: codex

#12863 Add icons for channelling menu
  src/main/webapp/resources/ezcomp/menu.xhtml
Labels: codex

#12865 Add icons to HR menu
  src/main/webapp/resources/ezcomp/menu.xhtml
Labels: codex

#12867 Add icons to EMR menu
  src/main/webapp/resources/ezcomp/menu.xhtml
Labels: codex

#12869 Add icons to reports menu
  src/main/webapp/resources/ezcomp/menu.xhtml
Labels: codex

#12877 Fix retail rate default for pack items
  src/main/java/com/divudi/bean/pharmacy/PharmacyDirectPurchaseController.java
Labels: codex

#12891 Add confirmations for Collecting Centre bill actions
  src/main/webapp/collecting_centre/bill.xhtml
  src/main/webapp/collecting_centre/bill_cancel.xhtml
  src/main/webapp/collecting_centre/bill_return.xhtml
  src/main/webapp/collecting_centre/collecting_centre_deposit_bill.xhtml
Labels: codex

#12896 Fix JSF references after method rename
  src/main/java/com/divudi/bean/optician/OpticianPurchaseController.java
  src/main/java/com/divudi/bean/pharmacy/PharmacyDirectPurchaseController.java
  src/main/java/com/divudi/bean/pharmacy/PharmacyPurchaseController.java
  src/main/webapp/optician/purchase.xhtml
  src/main/webapp/pharmacy/pharmacy_purchase.xhtml
  src/main/webapp/pharmacy_wholesale/pharmacy_purchase.xhtml
Labels: codex

#12898 Improve income bill counts UI
  src/main/java/com/divudi/bean/report/ReportController.java
  src/main/webapp/analytics/summaries/income_bill_counts.xhtml
Labels: codex

#12902 Add ScheduledProcess enum
  src/main/java/com/divudi/bean/common/EnumController.java
  src/main/java/com/divudi/core/data/ScheduledProcess.java
Labels: codex

#12904 Fix Movement Out report view case
  src/main/java/com/divudi/bean/pharmacy/PharmacySummaryReportController.java
Labels: codex

#12905 Add scheduled process configuration entity
  src/main/java/com/divudi/bean/common/EnumController.java
  src/main/java/com/divudi/core/data/ScheduledFrequency.java
  src/main/java/com/divudi/core/entity/ScheduledProcessConfiguration.java
Labels: codex

#12914 Add cost rate and value to batch stock report
  src/main/java/com/divudi/bean/pharmacy/ReportsStock.java
  src/main/webapp/pharmacy/pharmacy_report_department_stock_by_batch.xhtml
Labels: codex

#12916 Add stock value calculation service
  src/main/java/com/divudi/core/data/StockValueRow.java
  src/main/java/com/divudi/service/StockService.java
Labels: codex

#12919 Add historical record generation page
  src/main/java/com/divudi/bean/common/HistoricalRecordController.java
  src/main/java/com/divudi/service/HistoricalRecordService.java
  src/main/webapp/dataAdmin/admin_data_administration.xhtml
  src/main/webapp/dataAdmin/historical_record_generate.xhtml
Labels: codex

#12921 Add flush-aware historical record creation
  src/main/java/com/divudi/bean/common/HistoricalRecordController.java
  src/main/java/com/divudi/service/HistoricalRecordService.java
Labels: codex

#12926 Add scheduled process support
  src/main/java/com/divudi/core/entity/ScheduledProcessConfiguration.java
  src/main/java/com/divudi/service/ScheduledProcessService.java
  src/main/java/com/divudi/service/ScheduledTaskManager.java
Labels: codex

#12927 Implement scheduled pharmacy stock recording
  src/main/java/com/divudi/service/ScheduledProcessService.java
Labels: codex

#12934 Collection center book wise detail #12760
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/webapp/reports/collectionCenterReports/collection_centre_book_wise_detail.xhtml
Labels: bug

#12939 Add manual run option for scheduled processes
  src/main/java/com/divudi/bean/process/ScheduledProcessConfigurationController.java
  src/main/java/com/divudi/service/ScheduledProcessService.java
  src/main/webapp/process/admin/scheduled_process_configurations.xhtml
Labels: codex

#12945 Fix Manage User Icon removal
  src/main/java/com/divudi/bean/common/UserIconController.java
  src/main/java/com/divudi/bean/common/UserRoleIconController.java
Labels: codex

#12949 12947 year-end schedule fix
  README.md
  src/main/java/com/divudi/service/ScheduledProcessService.java
  src/test/java/com/divudi/service/ScheduledProcessServiceTest.java
Labels: codex

#12954 12942 differentiate runLastScheduled and runNextScheduled actions
  src/main/java/com/divudi/bean/process/ScheduledProcessConfigurationController.java
  src/main/java/com/divudi/service/ScheduledProcessService.java
Labels: codex

#12955 Resolve issue 12709
  src/main/java/com/divudi/bean/common/ConfigOptionApplicationController.java
  src/main/java/com/divudi/bean/pharmacy/TransferIssueController.java
Labels: codex

#12962 Add GRN costing controller
  src/main/java/com/divudi/bean/pharmacy/GrnCostingController.java
  src/main/webapp/pharmacy/pharmacy_grn_costing.xhtml
Labels: codex

#12963 Fix issue 12959
  src/main/webapp/home.xhtml
Labels: codex

#12965 Fix pharmacy sale without stock search
  src/main/java/com/divudi/bean/common/SearchController.java
Labels: codex

#12968 Update Goods Receipt navigation
  src/main/webapp/home.xhtml
  src/main/webapp/resources/ezcomp/menu.xhtml
Labels: codex

#12972 12957 add costing toggle for GRN receive
  src/main/java/com/divudi/bean/pharmacy/GrnCostingController.java
  src/main/webapp/pharmacy/pharmacy_purchase_order_list_for_recieve.xhtml
Labels: codex

#12993 Fix discount calculation and clean controller
  src/main/java/com/divudi/bean/pharmacy/GrnCostingController.java
  src/main/webapp/pharmacy/pharmacy_grn_costing.xhtml
Labels: codex

#12994 Fix GRN discount net total update
  src/main/java/com/divudi/bean/pharmacy/GrnCostingController.java
Labels: codex

#12995 Enhance BillExpense UX and validation
  src/main/java/com/divudi/bean/common/BillExpenseController.java
  src/main/webapp/admin/items/bill_expenses.xhtml
Labels: codex

#12997 Fix finance summary update on GRN costing page
  src/main/webapp/pharmacy/pharmacy_grn_costing.xhtml
Labels: codex

#13007 Add defaults for direct issue return options
  src/main/java/com/divudi/bean/common/ConfigOptionApplicationController.java
Labels: codex

#13009 Update return controllers to use configurable cost rate
  src/main/java/com/divudi/bean/pharmacy/GoodsReturnController.java
  src/main/java/com/divudi/bean/pharmacy/PurchaseReturnController.java
Labels: codex

#13011 Implement shared return rate helper
  src/main/java/com/divudi/bean/pharmacy/GoodsReturnController.java
  src/main/java/com/divudi/bean/pharmacy/PurchaseReturnController.java
Labels: codex

#13012 Collection center book wise detail #12985 & Closing Stock report #13004
  src/main/java/com/divudi/bean/common/ReportsController.java
  src/main/java/com/divudi/bean/report/PharmacyReportController.java
Labels: bug

#13020 Add total quantity mode for purchase returns
  src/main/java/com/divudi/bean/pharmacy/PurchaseReturnController.java
Labels: codex

#13021 Implement dynamic quantity headers in purchase return page
  src/main/webapp/pharmacy/pharmacy_return_purchase.xhtml
Labels: codex

#13024 Add purchase details panel
  src/main/webapp/pharmacy/pharmacy_return_purchase.xhtml
Labels: codex

#13022 Add bulk SMS to numbers feature
  src/main/java/com/divudi/bean/common/SmsController.java
  src/main/java/com/divudi/core/data/MessageType.java
  src/main/webapp/admin/users/index.xhtml
  src/main/webapp/admin/users/send_bulk_sms_numbers.xhtml
Labels: codex

#13025 Add description field for VMP admin
  src/main/webapp/pharmacy/admin/vmp.xhtml
Labels: codex

#13027 Add total quantity option for purchase returns
  src/main/webapp/resources/pharmacy/purchaseReturn.xhtml
Labels: codex

#13028 Add purchase bill view button on return page
  src/main/webapp/pharmacy/pharmacy_return_purchase.xhtml
Labels: codex

#13042 13029-update-query-for-zero-stock-items
  src/main/java/com/divudi/bean/pharmacy/ReportsStock.java
Labels: codex

#13052 Remove obsolete methods from direct purchase controller
  src/main/java/com/divudi/bean/pharmacy/PharmacyDirectPurchaseController.java
Labels: codex

#13058 Fix bill finance details initialization
  src/main/java/com/divudi/service/pharmacy/PharmacyCostingService.java
Labels: codex

#13059 Fix finance details refresh
  src/main/webapp/pharmacy/direct_purchase.xhtml
Labels: codex

#13063 Implement zero stock report navigation
  src/main/java/com/divudi/bean/pharmacy/ReportsStock.java
  src/main/webapp/pharmacy/pharmacy_analytics.xhtml
Labels: codex

#13066 Fix package bill cancellation privilege
  src/main/java/com/divudi/bean/common/BillPackageController.java
  src/main/java/com/divudi/core/data/Privileges.java
  src/main/webapp/opd/opd_package_batch_bill_print.xhtml
  src/main/webapp/opd/opd_package_bill_cancel.xhtml
Labels: codex

#13068 Add institution/site filters to zero stock report
  src/main/java/com/divudi/bean/pharmacy/ReportsStock.java
  src/main/webapp/pharmacy/pharmacy_analytics.xhtml
  src/main/webapp/pharmacy/pharmacy_report_department_stock_by_zero_item.xhtml
Labels: codex

#13072 13002-log-for-turning-on-and-off-of-configuration-options
  src/main/java/com/divudi/bean/common/ConfigOptionController.java
Labels: codex

#13073 Replace debug prints in AuditEvent
  src/main/java/com/divudi/core/entity/AuditEvent.java
Labels: codex

#13076 Add config option changes button to Audit tab
  src/main/webapp/dataAdmin/admin_data_administration.xhtml
Labels: codex

#13077 Add method to fetch config option audit events
  src/main/java/com/divudi/bean/common/AuditEventController.java
Labels: codex

#13078 Simplify BillExpenseFacade EntityManager retrieval
  src/main/java/com/divudi/bean/common/BillExpenseFacade.java
Labels: codex

#13079 Refactor wholesale rate calculation
  src/main/java/com/divudi/bean/pharmacy/GrnCostingController.java
Labels: codex

#13084 Update AGENTS with PR issue closing guidance
  AGENTS.md
Labels: codex

#13087 Fix spelling error in controller field
  src/main/java/com/divudi/bean/common/DepartmentController.java
  src/main/java/com/divudi/bean/common/UserDepartmentController.java
  src/main/java/com/divudi/bean/common/UserRouteController.java
  src/main/java/com/divudi/bean/pharmacy/ItemsDistributorsController.java
  src/main/java/com/divudi/bean/store/StoreItemsDistributorsController.java
  src/main/webapp/admin/users/user_department.xhtml
  src/main/webapp/admin/users/user_routes.xhtml
  src/main/webapp/dev/depts.xhtml
  src/main/webapp/pharmacy/pharmacy_items_distributors.xhtml
  src/main/webapp/store/store_items_distributors.xhtml
Labels: codex

#13093 Create finance details for direct purchase returns
  src/main/java/com/divudi/bean/pharmacy/DirectPurchaseReturnController.java
Labels: codex

#13094 Add null safety checks for store items distributors
  src/main/java/com/divudi/bean/store/StoreItemsDistributorsController.java
Labels: codex

#13097 Implement bill item detail calculation for returns
  src/main/java/com/divudi/bean/pharmacy/DirectPurchaseReturnController.java
Labels: codex

#13101 Closing Stock report #13004
  src/main/java/com/divudi/bean/report/PharmacyReportController.java
Labels: bug

#13105 Update pharmacy financial totals with cost rates
  src/main/java/com/divudi/service/BillService.java
Labels: codex

#13108 Fix duplicate settlement issue in pharmacy
  src/main/java/com/divudi/bean/pharmacy/PharmacyPreSettleController.java
  src/main/webapp/pharmacy/pharmacy_bill_pre_settle.xhtml
Labels: codex

#13113 Fix direct purchase return issues
  src/main/java/com/divudi/bean/common/BillSearch.java
  src/main/java/com/divudi/bean/pharmacy/DirectPurchaseReturnController.java
  src/main/webapp/pharmacy/direct_purchase_return.xhtml
  src/main/webapp/resources/pharmacy/purhcase.xhtml
Labels: codex

#13120 Fix duplicate bill settlement
  src/main/java/com/divudi/bean/common/OpdPreSettleController.java
  src/main/java/com/divudi/bean/pharmacy/PharmacyPreSettleController.java
Labels: codex

#13121 Ensure bills commit immediately on settle
  src/main/java/com/divudi/bean/common/OpdPreSettleController.java
  src/main/java/com/divudi/bean/pharmacy/PharmacyPreSettleController.java
Labels: codex

#13122 Prevent duplicate settleBillWithPay2 calls
  src/main/java/com/divudi/bean/common/OpdPreSettleController.java
  src/main/java/com/divudi/bean/pharmacy/PharmacyPreSettleController.java
Labels: codex

#13039 Need to compare requested drugs and issued drugs hotfix (DO NOT MERGE- Hotfix for SLH Prod)
  src/main/java/com/divudi/bean/common/EnumController.java
  src/main/java/com/divudi/bean/common/SmsController.java
  src/main/java/com/divudi/bean/inward/InwardReportControllerBht.java
  src/main/java/com/divudi/bean/inward/InwardSearch.java
  src/main/java/com/divudi/core/data/MessageType.java
  src/main/webapp/admin/users/index.xhtml
  src/main/webapp/admin/users/send_bulk_sms_numbers.xhtml
  src/main/webapp/admin/users/send_bulk_sms_patients.xhtml
  src/main/webapp/inward/inward_provisional_bill_edit.xhtml
  src/main/webapp/pharmacy/reports/inpatient_pharmacy_requested_item_overview_by_bill.xhtml
  src/main/webapp/resources/ezcomp/menu.xhtml
  src/main/webapp/resources/ezcomp/prints/five_five_custom_3.xhtml
Labels: Hot Fix

#13132 Improve return bill calculations
  src/main/java/com/divudi/bean/pharmacy/DirectPurchaseReturnController.java
  src/main/webapp/pharmacy/direct_purchase_return.xhtml
Labels: codex

#13134 Fix return bill calculations
  src/main/java/com/divudi/bean/pharmacy/DirectPurchaseReturnController.java
  src/main/webapp/pharmacy/direct_purchase_return.xhtml
Labels: codex

#13138 Fix return rate calculation
  src/main/java/com/divudi/bean/pharmacy/DirectPurchaseReturnController.java
Labels: codex

#13151 Reports disable hotfix
  src/main/webapp/pharmacy/pharmacy_analytics.xhtml
  src/main/webapp/pharmacy/pharmacy_report_grn_billitem.xhtml
  src/main/webapp/pharmacy/reports/summary_reports/pharmacy_income_and_cost_report.xhtml
Labels: Hot Fix

#13154 GRN report process button isn't working
  src/main/java/com/divudi/bean/pharmacy/PharmacyController.java
Labels: bug

#13156 External Laboratory Workload - Speed Improvement #13155
  src/main/java/com/divudi/bean/common/ReportsController.java
Labels: enhancement

#13164 Add PharmacyIncomeCostBillDTO
  src/main/java/com/divudi/core/data/dto/PharmacyIncomeCostBillDTO.java
Labels: codex

#13169 Add support for PharmacyIncomeCostBillDTO in IncomeBundle
  src/main/java/com/divudi/core/data/IncomeBundle.java
  src/main/java/com/divudi/core/data/IncomeRow.java
Labels: codex

#13170 Implement DTO-based pharmacy income cost calculation
  src/main/java/com/divudi/bean/pharmacy/PharmacySummaryReportController.java
Labels: codex

#13171 Update pharmacy income report to use bill DTO
  src/main/webapp/pharmacy/reports/summary_reports/pharmacy_income_and_cost_report.xhtml
Labels: codex

#13177 Implement DTO-based pharmacy income reporting
  src/main/java/com/divudi/bean/pharmacy/PharmacySummaryReportController.java
  src/main/java/com/divudi/core/data/IncomeBundle.java
  src/main/java/com/divudi/core/data/IncomeRow.java
  src/main/java/com/divudi/core/data/dto/PharmacyIncomeCostBillItemDTO.java
  src/main/java/com/divudi/service/BillService.java
  src/main/webapp/pharmacy/reports/summary_reports/pharmacy_income_and_cost_report.xhtml
Labels: codex

#13178 Replace nested bill fields with IncomeRow data
  src/main/webapp/pharmacy/reports/summary_reports/pharmacy_income_and_cost_report.xhtml
  src/main/webapp/pharmacy/reports/summary_reports/pharmacy_income_report.xhtml
  src/main/webapp/pharmacy/reports/summary_reports/pharmacy_income_report_print.xhtml
  src/main/webapp/pharmacy/reports/summary_reports/pharmacy_income_report_print_view.xhtml
Labels: codex

#13157 Cashier Summary report #12333
  src/main/java/com/divudi/bean/common/ExcelController.java
  src/main/webapp/reports/cashier_reports/cashier_summary.xhtml
Labels: Urgent, Report, Ruhunu Hospital

#13165 Stock report by item order by vmp report #13159
  src/main/webapp/pharmacy/pharmacy_analytics.xhtml
  src/main/webapp/pharmacy/pharmacy_report_department_stock_by_item_order_by_vmp.xhtml
Labels: Pharmacy, Report, COOP Hospital

#13168 Category Stock Summary Report #13161
  src/main/webapp/pharmacy/pharmacy_analytics.xhtml
Labels: Pharmacy, Report, COOP Hospital

#13163 Online booking payment management feature
  src/main/java/com/divudi/bean/channel/BookingController.java
  src/main/java/com/divudi/bean/channel/BookingControllerViewScope.java
  src/main/java/com/divudi/bean/channel/OnlineBookingAgentController.java
  src/main/java/com/divudi/core/data/BillType.java
  src/main/java/com/divudi/core/data/BillTypeAtomic.java
  src/main/java/com/divudi/core/data/InstitutionType.java
  src/main/java/com/divudi/core/data/OnlineBookingStatus.java
  src/main/java/com/divudi/core/entity/OnlineBooking.java
  src/main/java/com/divudi/service/ChannelService.java
  src/main/java/com/divudi/ws/channel/ChannelApi.java
  src/main/resources/META-INF/persistence.xml
  src/main/webapp/admin/institutions/institution_management.xhtml
  src/main/webapp/channel/channel_booking.xhtml
  src/main/webapp/channel/channel_booking_by_date.xhtml
  src/main/webapp/channel/reports/online_session_booking_count.xhtml
  src/main/webapp/online_booking_agent_management/OB_agent_management.xhtml
  src/main/webapp/online_booking_agent_management/OB_agent_paid_bill_reprint.xhtml
  src/main/webapp/online_booking_agent_management/OB_payment_bill_search.xhtml
  src/main/webapp/online_booking_agent_management/OB_payment_handle.xhtml
  src/main/webapp/online_booking_agent_management/index.xhtml
  src/main/webapp/online_booking_agent_management/view_all_online_bookings.xhtml
  src/main/webapp/resources/channel/agentPaidToHospitalBill.xhtml
  src/main/webapp/resources/ezcomp/menu.xhtml
Labels: Channelling

#13215 12875-fill-pharmacy-bill-finance-details
  src/main/java/com/divudi/bean/pharmacy/PharmacySummaryReportController.java
  src/test/java/com/divudi/bean/pharmacy/PharmacySummaryReportControllerTest.java
Labels: codex

#13198 Add_service_department_and_institution-hotfix (do not merge)
  src/main/java/com/divudi/bean/report/ReportController.java
  src/main/webapp/pharmacy/reports/disbursement_reports/pharmacy_report_transfer_issue_bill_summery.xhtml
  src/main/webapp/reports/managementReports/referring_doctor_wise_revenue.xhtml
Labels: Hot Fix

#13216 Transfer issue by bill summary report #13186
  src/main/webapp/pharmacy/reports/disbursement_reports/pharmacy_report_transfer_issue_bill_summery.xhtml
  src/main/webapp/pharmacy/reports/disbursement_reports/pharmacy_report_transfer_issue_bill_summery_print.xhtml
Labels: Pharmacy, Report, COOP Hospital

#13218 Supplier's expiring stocks report #13187
  src/main/webapp/pharmacy/pharmacy_analytics.xhtml
  src/main/webapp/pharmacy/pharmacy_report_supplier_expiary_stock_by_batch.xhtml
  src/main/webapp/pharmacy/pharmacy_report_supplier_expiary_stock_by_batch_print.xhtml
Labels: Pharmacy, Report, COOP Hospital

#13233 Implement bill item finance detail calculations
  src/main/java/com/divudi/bean/pharmacy/PharmacySummaryReportController.java
Labels: codex

#13229 Consumption #13225 Stock Transfers #13226 Good In Transit #13227 GRN Report #13228
  src/main/java/com/divudi/bean/pharmacy/PharmacyController.java
  src/main/webapp/reports/inventoryReports/consumption.xhtml
  src/main/webapp/reports/inventoryReports/good_in_transit.xhtml
  src/main/webapp/reports/inventoryReports/grn_report.xhtml
  src/main/webapp/reports/inventoryReports/stock_transfer_report.xhtml
Labels: bug

#13275 Fix #13273 - date range filter not working
  src/main/java/com/divudi/bean/pharmacy/PharmacyController.java
  src/main/webapp/pharmacy/pharmacy_analytics.xhtml
  src/main/webapp/pharmacy/pharmacy_item_transactions.xhtml
Labels: codex

#13278 Agent channel booking report #13258
  src/main/webapp/channel/agent_channel_bookings.xhtml
  src/main/webapp/channel/agent_channel_bookings_print.xhtml
Labels: Urgent, Channelling, Report, COOP Hospital

#13252 Hotfix for COOP PROD
  src/main/webapp/opd/opd_batch_bill_print.xhtml
Labels: Hot Fix

#13303 #13214 cost of good sold
  src/main/java/com/divudi/bean/report/PharmacyReportController.java
Labels: Pharmacy, Report, Ruhunu Hospital

#13263 Real time update for channel bookings
  src/main/java/com/divudi/bean/channel/BookingController.java
  src/main/java/com/divudi/bean/channel/BookingControllerViewScope.java
  src/main/java/com/divudi/service/ChannelService.java
  src/main/java/com/divudi/service/WebSocketService.java
  src/main/java/com/divudi/ws/channel/ChannelApi.java
  src/main/resources/META-INF/persistence.xml
  src/main/webapp/channel/channel_booking.xhtml
  src/main/webapp/channel/channel_booking_by_date.xhtml
  src/main/webapp/channel/session_instance.xhtml
Labels: Channelling

#13334 12890-transfer-issue-receipt-template
  src/main/java/com/divudi/bean/common/ConfigOptionApplicationController.java
  src/main/webapp/resources/pharmacy/pharmacy_transfer_issue_receipt.xhtml
Labels: codex

#13292 Need to replace and issue drugs other than the requested ones from ward hotfix ( DO NOT MERGE - HOTFIX FOR SLH)
  src/main/java/com/divudi/bean/pharmacy/PharmacySaleBhtController.java
  src/main/webapp/ward/ward_pharmacy_bht_issue.xhtml
Labels: Hot Fix

#13339 #13287 add free items and expiry columns for single item summary hotfix
  src/main/webapp/pharmacy/pharmacy_item_transactions.xhtml
  src/main/webapp/reports/managementReports/referring_doctor_wise_revenue.xhtml
Labels: Hot Fix

#13338 Improvement in real time updates feature
  src/main/webapp/channel/channel_booking.xhtml
  src/main/webapp/channel/channel_booking_by_date.xhtml
  src/main/webapp/channel/session_instance.xhtml
Labels: Channelling

#13340 Before quantity in duplicate adjustment bill is wrong hotfix
  src/main/java/com/divudi/bean/pharmacy/PharmacyAdjustmentController.java
  src/main/webapp/pharmacy/pharmacy_search_adjustment_bill_item.xhtml
  src/main/webapp/resources/pharmacy/adjustmentBill.xhtml
Labels: Hot Fix

#13335 Add patient Edit privilage (do not Marge)
  src/main/webapp/opd/patient.xhtml
  src/main/webapp/opd/patient_edit.xhtml
  src/main/webapp/opd/patient_search.xhtml
Labels: OPD, Lab, Southern Lanka Hospital, Hot Fix

#13280 13277 add support to aia 360 analyzer hotfix - After discussing with Southern Lanka for a Downtime
  pom.xml
  src/main/java/com/divudi/core/data/lab/Analyzer.java
  src/main/java/com/divudi/ws/lims/LimsMiddlewareController.java
  src/main/java/com/divudi/ws/lims/MiddlewareController.java
  src/main/resources/META-INF/persistence_for_database_generation_script.xml
  src/main/webapp/WEB-INF/glassfish-web.xml
Labels: Hot Fix

#13346 Signed-off-by: Lawan Samarasekara <lawan.chaamindu1234@gmail.com>
  src/main/webapp/resources/pharmacy/adjustmentBill.xhtml
Labels: Hot Fix

#13354 Added pharmacy bills to staff welfare report
  src/main/java/com/divudi/bean/common/SearchController.java
Labels: enhancement

#13364 #13211 cogs sale credit card
  src/main/java/com/divudi/bean/report/PharmacyReportController.java
  src/main/webapp/reports/inventoryReports/opd_credit.xhtml
  src/main/webapp/reports/inventoryReports/opd_sale.xhtml
Labels: Report, Ruhunu Hospital

#13369 Fixed - patient Data Edit Privilage
  src/main/webapp/opd/patient.xhtml
  src/main/webapp/opd/patient_edit.xhtml
Labels: Hot Fix

#13370 13365 if edit privileges are not granted access to patient lookup and registration will be restricted
  src/main/webapp/opd/patient.xhtml
  src/main/webapp/opd/patient_edit.xhtml
Labels: Southern Lanka Hospital

#13376 Channel scaning session bug fixing
  src/main/java/com/divudi/bean/channel/BookingControllerViewScope.java
  src/main/webapp/channel/manage_booking_by_date.xhtml
Labels: Channelling

#13381 Cost Of Good Sold - Transfer Receive #13210
  src/main/webapp/reports/inventoryReports/transfer_receive.xhtml
Labels: Report, Ruhunu Hospital

#13390 Consumption #13246
  src/main/java/com/divudi/bean/pharmacy/PharmacyController.java
  src/main/java/com/divudi/core/data/reports/InventoryReports.java
  src/main/webapp/reports/inventoryReports/consumption.xhtml
Labels: bug

#13393 Pharmacy staff welfare #13391
  src/main/java/com/divudi/bean/common/SearchController.java
Labels: bug

#13405 Need to add missed bill type atomic to get data in bill count list report hotfix
  src/main/java/com/divudi/bean/common/SearchController.java
Labels: Hot Fix

#13410 Fix TransferIssue empty bill save check
  src/main/java/com/divudi/bean/pharmacy/TransferIssueController.java
Labels: codex

#13425 Remove stray lines from ConfigOption
  src/main/java/com/divudi/core/entity/ConfigOption.java
Labels: codex

#13424 Handle duplicate ConfigOption records
  src/main/java/com/divudi/bean/common/ConfigOptionApplicationController.java
  src/main/java/com/divudi/bean/common/ConfigOptionController.java
  src/main/java/com/divudi/core/entity/ConfigOption.java
  src/main/java/com/divudi/core/facade/ConfigOptionFacade.java
  src/main/java/com/divudi/service/ConfigurationService.java
  src/main/webapp/admin/institutions/admin_institutions_index.xhtml
  src/main/webapp/admin/institutions/config_option_duplicates.xhtml
  src/main/webapp/resources/sql/retire_config_option_duplicates.sql
Labels: codex

#13426 Refactor config option retrieval to single source
  src/main/java/com/divudi/service/ConfigurationService.java
  src/main/java/com/divudi/service/DrawerService.java
Labels: codex

#13436 Add bulk convert investigations to services
  src/main/java/com/divudi/bean/lab/InvestigationController.java
  src/main/webapp/dataAdmin/lab_investigation_list.xhtml
Labels: codex

#13438 13435: GRN costing rounding fix
  src/main/java/com/divudi/ejb/PharmacyCalculation.java
Labels: codex

#13442 13357-should-not-allow-to-add-expired-items-in-direct-purchase
  src/main/java/com/divudi/bean/pharmacy/PharmacyDirectPurchaseController.java
Labels: codex

#13444 Implement item history view button
  AGENTS.md
  src/main/java/com/divudi/bean/pharmacy/PurchaseOrderRequestController.java
  src/main/webapp/pharmacy/pharmacy_purhcase_order_request.xhtml
Labels: codex

#13446 Add configurable rendering for pharmacy history tabs
  src/main/webapp/resources/pharmacy/history.xhtml
Labels: codex

#13447 Consolidate pharmacy sales queries
  src/main/java/com/divudi/bean/pharmacy/PharmacyController.java
Labels: codex

#13454 Implement duplicate institution detection
  src/main/java/com/divudi/bean/common/InstitutionController.java
  src/main/webapp/admin/institutions/admin_institutions_index.xhtml
  src/main/webapp/admin/institutions/institution_duplicates.xhtml
Labels: codex

#13455 Detect and handle duplicate departments
  src/main/java/com/divudi/bean/common/DepartmentController.java
  src/main/webapp/admin/institutions/admin_institutions_index.xhtml
  src/main/webapp/admin/institutions/department_duplicates.xhtml
Labels: codex

#13481 Fix invoice detail loss in GRN costing
  src/main/webapp/pharmacy/pharmacy_grn_costing.xhtml
Labels: codex
